.ci/helm.sh
charts/local-storage-provisioner/Chart.yaml
charts/pulsar/Chart.yaml
charts/pulsar/values.yaml

Upgrade the version to 1.0.0

---

.ci/clusters/values-pulsar-image.yaml
.ci/helm.sh
.github/workflows/pulsar_image.yml
charts/pulsar/templates/bookkeeper-autorecovery-statefulset.yaml
charts/pulsar/templates/bookkeeper-cluster-initialize.yaml
charts/pulsar/templates/bookkeeper-statefulset.yaml
charts/pulsar/templates/broker-configmap.yaml
charts/pulsar/templates/broker-statefulset.yaml
charts/pulsar/templates/proxy-configmap.yaml
charts/pulsar/templates/proxy-statefulset.yaml
charts/pulsar/templates/pulsar-cluster-initialize.yaml
charts/pulsar/templates/toolset-statefulset.yaml
charts/pulsar/templates/zookeeper-statefulset.yaml
charts/pulsar/values.yaml
examples/pulsar/values-one-node.yaml
examples/pulsar/values-pulsar.yaml

- support both sn-platform and pulsar images
- add readiness and liveness probe

Support dural images and add probe

---

.ci/clusters/values-tls.yaml
.ci/helm.sh
charts/pulsar/templates/_autorecovery.tpl
charts/pulsar/templates/_bookkeeper.tpl
charts/pulsar/templates/_broker.tpl
charts/pulsar/templates/_helpers.tpl
charts/pulsar/templates/_toolset.tpl
charts/pulsar/templates/_zookeeper.tpl
charts/pulsar/templates/bookkeeper-autorecovery-configmap.yaml
charts/pulsar/templates/bookkeeper-autorecovery-statefulset.yaml
charts/pulsar/templates/bookkeeper-cluster-initialize.yaml
charts/pulsar/templates/bookkeeper-configmap.yaml
charts/pulsar/templates/bookkeeper-statefulset.yaml
charts/pulsar/templates/broker-configmap.yaml
charts/pulsar/templates/broker-statefulset.yaml
charts/pulsar/templates/proxy-configmap.yaml
charts/pulsar/templates/pulsar-cluster-initialize.yaml
charts/pulsar/templates/tls-certs-internal.yaml
charts/pulsar/templates/toolset-configmap.yaml
charts/pulsar/templates/toolset-statefulset.yaml
charts/pulsar/templates/zookeeper-configmap.yaml
charts/pulsar/templates/zookeeper-service.yaml
charts/pulsar/templates/zookeeper-statefulset.yaml
charts/pulsar/values.yaml
examples/pulsar/values-tls.yaml

- Enable TLS on zookeeper
- Configure all components to talk to zookeeper using TLS

Enable TLS on zookeeper

---

.github/workflows/pulsar.yml
.github/workflows/pulsar_bk_tls.yml
.github/workflows/pulsar_broker_tls.yml
.github/workflows/pulsar_function.yml
.github/workflows/pulsar_image.yml
.github/workflows/pulsar_jwt_asymmetric.yml
.github/workflows/pulsar_jwt_symmetric.yml
.github/workflows/pulsar_tls.yml
.github/workflows/pulsar_zk_tls.yml
.github/workflows/pulsar_zkbk_tls.yml

---
*Motivation*
Currently, the CI process failed with `Error: Error running process: exit status 128`.

Fix CI error

---

charts/pulsar/templates/_autorecovery.tpl
charts/pulsar/templates/_bookkeeper.tpl
charts/pulsar/templates/_broker.tpl
charts/pulsar/templates/_proxy.tpl
charts/pulsar/templates/_pulsar_manager.tpl
charts/pulsar/templates/_toolset.tpl
charts/pulsar/templates/_zookeeper.tpl
charts/pulsar/templates/presto-coordinator-statefulset.yaml
charts/pulsar/templates/presto-worker-statefulset.yaml
charts/pulsar/templates/tls-cert-internal-issuer.yaml
charts/pulsar/templates/tls-certs-internal.yaml
charts/pulsar/templates/tls-certs-public.yaml

---
*Motivation*
Make the secret name aligned with the secret names generated by the
`prepare_helm_release.sh`.

Update secret name to align with auto generate secret name

---

charts/pulsar/templates/_autorecovery.tpl
charts/pulsar/templates/_bookkeeper.tpl
charts/pulsar/templates/_broker.tpl
charts/pulsar/templates/_proxy.tpl
charts/pulsar/templates/_toolset.tpl
charts/pulsar/templates/_zookeeper.tpl
charts/pulsar/templates/bookkeeper-cluster-initialize.yaml
charts/pulsar/templates/broker-cluster-role-binding.yaml
charts/pulsar/templates/broker-configmap.yaml
charts/pulsar/templates/broker-service.yaml
charts/pulsar/templates/broker-statefulset.yaml
charts/pulsar/templates/keytool.yaml
charts/pulsar/templates/proxy-statefulset.yaml
charts/pulsar/templates/pulsar-cluster-initialize.yaml
charts/pulsar/templates/pulsar-manager-initialize.yaml
charts/pulsar/templates/tls-certs-internal.yaml
charts/pulsar/templates/toolset-configmap.yaml
charts/pulsar/templates/toolset-statefulset.yaml
charts/pulsar/values.yaml

*Changes*
- Enable TLS & Authentication
- Add flags to control whether to run init jobs
- Fix broker cluster role binding
- Fix log configmap volume name

Enable TLS & Authentication for KoP

---

charts/pulsar/templates/_broker.tpl
charts/pulsar/templates/broker-configmap.yaml
charts/pulsar/templates/broker-statefulset.yaml
charts/pulsar/values.yaml

- Enable custom runtime options

Enable custom runtime options

---

charts/pulsar/templates/grafana-deployment.yaml
charts/pulsar/values.yaml

Fix #56 
- Add Loki datasource to helm

Add Loki datasource to helm

---

charts/pulsar/templates/_proxy.tpl
charts/pulsar/templates/proxy-statefulset.yaml

---
*Motivation*
Add datadog annotation in proxy.

Add proxy datadog annotation

---

charts/pulsar/templates/_control_center.tpl
charts/pulsar/templates/_toolset.tpl
charts/pulsar/templates/alertmanager-statefulset.yaml
charts/pulsar/templates/bookkeeper-service.yaml
charts/pulsar/templates/grafana-deployment.yaml
charts/pulsar/templates/prometheus-statefulset.yaml
charts/pulsar/templates/proxy-service.yaml
charts/pulsar/templates/pulsar-manager-configmap.yaml
charts/pulsar/templates/toolset-configmap.yaml
charts/pulsar/templates/toolset-statefulset.yaml
charts/pulsar/values.yaml

*Motivation*
A DNS entry can be added to the control-center ingress later. So we need to provide the ability for configuring an external DNS entry for the control-center.

Support external service url

---

charts/pulsar/templates/image-puller/_daemonset-helper.yaml
charts/pulsar/templates/image-puller/daemonset.yaml
charts/pulsar/templates/image-puller/job.yaml
charts/pulsar/templates/image-puller/rbac.yaml
charts/pulsar/values.yaml
images/image-awaiter/Dockerfile
images/image-awaiter/daemonset.go
images/image-awaiter/main.go

*Motivation*
Make sure the images are ready before upgrading the helm chart

Add image puller to pull images before installing or upgrading the helm chart

---

charts/pulsar/templates/prometheus-configmap.yaml
charts/pulsar/templates/pulsar-detector-pdb.yaml
charts/pulsar/templates/pulsar-detector-service-account.yaml
charts/pulsar/templates/pulsar-detector-service.yaml
charts/pulsar/templates/pulsar-detector-statefulset.yaml
charts/pulsar/values.yaml

Add pulsar detector to repo

---

README.md
scripts/pulsar/prepare_helm_release.sh

Fixes: #96 
- Fix the grafana canot login

[Issue:96] Fix the grafana canot login

---

charts/pulsar/templates/bookkeeper/bookkeeper-autorecovery-statefulset.yaml
charts/pulsar/templates/bookkeeper/bookkeeper-statefulset.yaml
charts/pulsar/templates/broker/broker-statefulset.yaml
charts/pulsar/templates/proxy/proxy-statefulset.yaml
charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml
charts/pulsar/values.yaml

*Motivation*
Allow pulsar components to configure securityContext and add extra initContainers

Add security context and extra init containers

---

charts/pulsar/Chart.yaml

Bumping helm chart to 1.2.1 to roll out #108

---

charts/pulsar/templates/zookeeper/_zookeeper.tpl
charts/pulsar/templates/zookeeper/gen-zk-conf.yaml
charts/pulsar/templates/zookeeper/zookeeper-configmap.yaml
charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml
charts/pulsar/values.yaml

*Motivation*
Support zookeeper statefulset to join an existing zookeeper cluster as observers

Allow zookeeper statefulset to join an existing zookeeper cluster as observers

---

charts/pulsar/templates/bookkeeper/bookkeeper-storageclass.yaml
charts/pulsar/templates/grafana/grafana-deployment.yaml
charts/pulsar/templates/zookeeper/zookeeper-storageclass.yaml
charts/pulsar/values.yaml

*Motivation*
Add more fields in the storage class to allow tuning storage class

Add more fields in the storage class

---

.ci/ct.sh
.github/workflows/pulsar.yml
.github/workflows/pulsar_bk_tls.yml
.github/workflows/pulsar_broker_tls.yml
.github/workflows/pulsar_function.yml
.github/workflows/pulsar_image.yml
.github/workflows/pulsar_jwt_asymmetric.yml
.github/workflows/pulsar_jwt_symmetric.yml
.github/workflows/pulsar_tls.yml
.github/workflows/pulsar_zk_tls.yml
.github/workflows/pulsar_zkbk_tls.yml
charts/pulsar/templates/broker/broker-configmap.yaml
charts/pulsar/templates/proxy/_proxy.tpl
charts/pulsar/templates/proxy/_websocket.tpl
charts/pulsar/templates/proxy/proxy-service-ingress.yaml
charts/pulsar/templates/proxy/proxy-service.yaml
charts/pulsar/templates/proxy/proxy-statefulset.yaml
charts/pulsar/templates/proxy/websocket-configmap.yaml
charts/pulsar/values.yaml
hack/kind-cluster-build.sh

Enable websocket in the proxy pods

---

.ci/helm.sh
charts/pulsar/values.yaml

Don't manage k8s namespace in helm charts

---

charts/pulsar/templates/alert-manager/alertmanager-statefulset.yaml
charts/pulsar/templates/bookkeeper/bookkeeper-autorecovery-statefulset.yaml
charts/pulsar/templates/bookkeeper/bookkeeper-statefulset.yaml
charts/pulsar/templates/broker/broker-statefulset.yaml
charts/pulsar/templates/control-center/ingress-controller-deployment.yaml
charts/pulsar/templates/detector/pulsar-detector-statefulset.yaml
charts/pulsar/templates/grafana/grafana-deployment.yaml
charts/pulsar/templates/node-exporter/node-exporter.yaml
charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml
charts/pulsar/templates/presto/presto-worker-statefulset.yaml
charts/pulsar/templates/prometheus/prometheus-statefulset.yaml
charts/pulsar/templates/proxy/proxy-statefulset.yaml
charts/pulsar/templates/pulsar-manager/pulsar-manager-statefulset.yaml
charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml

Since docker hub has pull request rate limiting, we have setup artifactory to serve the same images.  I can change the image repository to point to my own docker-hub proxy but the templates need to support imagePullSecrets.  I have update most of the templates except Pulsar Function.  Would appreciates the streamnative team review this PR and test it out.  If this is an acceptable approach, please advice on how to do the same for Pulsar Function.
```
##
images:
zookeeper:
repository: streamnative/pulsar-all
tag: 2.6.2.3
pullPolicy: IfNotPresent
bookie:
repository: streamnative/pulsar-all
tag: 2.6.2.3
pullPolicy: IfNotPresent
presto:
repository: streamnative/pulsar-all
tag: 2.6.2.3
pullPolicy: IfNotPresent
autorecovery:
repository: streamnative/pulsar-all
tag: 2.6.2.3
pullPolicy: …
```

adding support for imagePullSecrets

---

charts/pulsar/templates/broker/broker-configmap.yaml
charts/pulsar/templates/broker/broker-statefulset.yaml
charts/pulsar/templates/presto/presto-coordinator-configmap.yaml
charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml
charts/pulsar/templates/presto/presto-worker-configmap.yaml
charts/pulsar/templates/presto/presto-worker-statefulset.yaml
charts/pulsar/values.yaml

Support use static aws credential and support presto reading from tiered storage

---

charts/pulsar/templates/pulsar-cluster-initialize.yaml

---
Fixes #206
*Motivation*
Allow the use TLS connection to cleanup metadata in metadata tool

Support configure TLS for the metadata tool

---

charts/pulsar/templates/alert-manager/alertmanager-service.yaml
charts/pulsar/templates/detector/pulsar-detector-service.yaml
charts/pulsar/templates/grafana/grafana-service.yaml
charts/pulsar/templates/tls/tls-certs-internal.yaml
charts/pulsar/values.yaml

---
*Motivation*
- Fixes the incompatibility field for upgrading from apache charts, because the helm can not change the default value in the sub-values file, we comment the spec to make user can change it in the sub values file.
https://github.com/helm/helm/issues/9136
- Fixes the common name

Fixes the incompatibility field for upgrading from apache charts

---

charts/local-storage-provisioner/templates/provisioner-gke.yaml

from `extensions/v1beta1` to `apps/v1`

update apiversion for daemonset in local storage template

---

charts/pulsar/templates/zookeeper/zookeeper-backup-configmap.yaml
charts/pulsar/templates/zookeeper/zookeeper-restore-configmap.yaml
charts/pulsar/values.yaml

---
*Motivation*
Allow configure the bakcup/restore configurations by values.yaml.

Allow configure the backup/restore configurations by values.yaml

---

charts/pulsar/templates/zookeeper/_backup_restore.tpl
charts/pulsar/templates/zookeeper/zookeeper-backup-clusterrolebinding.yaml
charts/pulsar/templates/zookeeper/zookeeper-backup-rolebinding.yaml
charts/pulsar/templates/zookeeper/zookeeper-backup-serviceaccount.yaml
charts/pulsar/templates/zookeeper/zookeeper-backup-statefulset.yaml
charts/pulsar/templates/zookeeper/zookeeper-restore-clusterrolebinding.yaml
charts/pulsar/templates/zookeeper/zookeeper-restore-configmap.yaml
charts/pulsar/templates/zookeeper/zookeeper-restore-rolebinding.yaml
charts/pulsar/templates/zookeeper/zookeeper-restore-serviceaccount.yaml
charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml
charts/pulsar/values.yaml

Allow using service account to bind IAM role to access AWS service.

Support backup/restore tool use serviceAccount to connect to aws

---

charts/pulsar/templates/proxy/proxy-cluster.yaml
charts/pulsar/values.yaml

---
*Motivation*
Make the charts can enable the TLS with pulsar operator.
*Modifications*
Expose the `certSecretName` for allowing configure the TLS

Allow enable the TLS with pulsar operator

---

charts/function-mesh-operator/Chart.yaml
charts/pulsar-operator/values.yaml
charts/sn-pulsar/conf/vault/init_vault_streamnative_console/startup.sh
charts/sn-pulsar/requirements.yaml
charts/sn-pulsar/templates/broker/_broker.tpl
charts/sn-pulsar/templates/broker/broker-cluster.yaml
charts/sn-pulsar/templates/control-center/control-center-ingress.yaml
charts/sn-pulsar/templates/detector/pulsar-detector-statefulset.yaml
charts/sn-pulsar/templates/proxy/proxy-cluster.yaml
charts/sn-pulsar/templates/pulsar-cluster-initialize.yaml
charts/sn-pulsar/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-pulsar/templates/toolset/_toolset.tpl
charts/sn-pulsar/templates/vault/_vault.tpl
charts/sn-pulsar/templates/vault/vault-initialize.yaml
charts/sn-pulsar/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-pulsar/values.yaml

- Fix some bug in sn-pulsar chart

Update snpe charts

---

charts/function-mesh-operator/Chart.yaml
charts/function-mesh-operator/templates/controller-manager-deployment.yaml
charts/function-mesh-operator/templates/controller-manager-rbac.yaml
charts/function-mesh-operator/values.yaml
charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/templates/bookkeeper-operator/bookkeeper.streamnative.io_bookkeeperclusters_crd.yaml
charts/pulsar-operator/templates/bookkeeper-operator/operator.yaml
charts/pulsar-operator/templates/bookkeeper-operator/rbac.yaml
charts/pulsar-operator/templates/namespace.yaml
charts/pulsar-operator/templates/pulsar-operator/operator.yaml
charts/pulsar-operator/templates/pulsar-operator/pulsar.streamnative.io_pulsarbrokers_crd.yaml
charts/pulsar-operator/templates/pulsar-operator/pulsar.streamnative.io_pulsarproxies_crd.yaml
charts/pulsar-operator/templates/pulsar-operator/pulsar_broker_clusterrole.yaml
charts/pulsar-operator/templates/pulsar-operator/rbac.yaml
charts/pulsar-operator/templates/zookeeper-operator/operator.yaml
charts/pulsar-operator/templates/zookeeper-operator/rbac.yaml
charts/pulsar-operator/templates/zookeeper-operator/zookeeper.streamnative.io_zookeeperclusters_crd.yaml
charts/pulsar-operator/values.yaml
charts/sn-pulsar/values.yaml
license_test.go

**Motivation**
Fix the CI failure
**Modification**
- Add the license header for the files
- Skip crd directory license check

Fix the CI error

---

charts/pulsar/Chart.yaml
charts/pulsar/templates/bookkeeper/bookkeeper-cluster-initialize.yaml

Fix the indentation in bookkeeper-cluster-initialize and bump charts version

---

README.md
charts/function-mesh-operator/README.md
charts/image-puller/README.md
charts/local-storage-provisioner/README.md
charts/pulsar-operator/README.md
charts/pulsar/README.md
charts/sn-platform/README.md
docs/pulsar/install/deployment.md
docs/pulsar/install/gke.md

As there are multiple charts in this repo, we need to provide a concise and clear information for the users. Therefore, I add or update the READMEs for each chart.
also fixes #250 
- In the main README doc, give a general information about which charts are included in this repo, what the charts are used for, and give a link to specific charts README doc.
- Add new or update existing README docs for each charts.
- Add some tutorial guides for the `pulsar` chart

Update READMEs for different charts

---

charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml

---
*Modifications*
Update the presto coodinator service to the corresponds service name.

Fix the presto coordinator service name

---

charts/pulsar/templates/broker/broker-configmap.yaml

To get around KoP issue: https://github.com/apache/pulsar/pull/11014

[KOP] Set append timestamp interceptor

---

docs/pulsar/external_dns.md
docs/pulsar/install/deployment.md

Signed-off-by: floknip <florian.knip@lego.com>

fix typo in readme for external-dns installation

---

charts/pulsar/templates/broker/broker-configmap.yaml
charts/pulsar/templates/broker/broker-service-ingress.yaml
charts/pulsar/templates/broker/broker-service.yaml
charts/pulsar/templates/broker/broker-statefulset.yaml
charts/pulsar/values.yaml

TLS-PSK is introduced since sn-pulsar:2.8.1.1

[MOP] Support TLS-PSK

---

charts/pulsar/templates/presto/presto-coordinator-configmap.yaml
charts/pulsar/templates/presto/presto-worker-configmap.yaml
charts/sn-platform/templates/presto/presto-coordinator-configmap.yaml
charts/sn-platform/templates/presto/presto-worker-configmap.yaml

This fixes the settings for JDK 11... though I realized just now this might break for non JDK 11 images.
Any thoughts on how we should support that?

fix presto for JDK 11

---

charts/sn-platform/templates/grafana/grafana-configmap.yaml
charts/sn-platform/values.yaml

Reference https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L545
* Fixed custom grafana configuration file
* Add Azure AD configuration

Fixed custom grafana configuration file

---

.github/workflows/release.yml
charts/sn-platform/Chart.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/broker/broker-secret.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/proxy/proxy-secret.yaml
charts/sn-platform/values.yaml

Fixed support oauth for snp 2

---

charts/sn-platform/Chart.yaml
charts/sn-platform/values.yaml

* Upgrade pulsar and charts version

Upgrade pulsar and charts version

---

charts/sn-console/templates/console/streamnative-console-initialize.yaml
charts/sn-console/templates/console/streamnative-console-statefulset.yaml
charts/sn-console/values.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-google-oauth2-secret.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/values.yaml

* Set default value is false
* Add google oauth2 secret file

Fixed google oauth2 login failed bug

---

charts/pulsar/templates/bookkeeper/bookkeeper-cluster-role-binding.yaml
charts/pulsar/templates/bookkeeper/bookkeeper-role-binding.yaml
charts/pulsar/templates/broker/broker-role-binding.yaml
charts/pulsar/templates/control-center/ingress-controller-rbac.yaml
charts/pulsar/templates/external-dns/external-dns-rbac.yaml
charts/pulsar/templates/prometheus/pulsar-operators-rbac.yaml
charts/pulsar/templates/zookeeper/zookeeper-backup-clusterrolebinding.yaml
charts/pulsar/templates/zookeeper/zookeeper-backup-rolebinding.yaml
charts/pulsar/templates/zookeeper/zookeeper-restore-clusterrolebinding.yaml
charts/pulsar/templates/zookeeper/zookeeper-restore-rolebinding.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster-role-binding.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-role-binding.yaml
charts/sn-platform/templates/broker/broker-cluster-role-binding.yaml
charts/sn-platform/templates/broker/broker-role-binding.yaml
charts/sn-platform/templates/control-center/ingress-controller-rbac.yaml
charts/sn-platform/templates/external-dns/external-dns-rbac.yaml
charts/sn-platform/templates/prometheus/pulsar-operators-rbac.yaml
charts/sn-platform/templates/zookeeper/zookeeper-backup-clusterrolebinding.yaml
charts/sn-platform/templates/zookeeper/zookeeper-backup-rolebinding.yaml
charts/sn-platform/templates/zookeeper/zookeeper-restore-clusterrolebinding.yaml
charts/sn-platform/templates/zookeeper/zookeeper-restore-rolebinding.yaml
charts/sn-platform/values.yaml

Should be safe as rbac.authorization.k8s.io/v1 is available isnce k8s v1.8

Update pulsar/sn-platform chart to use rbacv1 api.

---

charts/pulsar/templates/grafana/grafana-configmap.yaml
charts/pulsar/templates/grafana/grafana-statefulset.yaml
charts/pulsar/values.yaml
charts/sn-platform/values.yaml

* Support custom grafana configuration

Support custom grafana configuration

---

charts/sn-platform/Chart.yaml

Upgrade sn platform version

---

charts/sn-console/Chart.yaml
charts/sn-console/values.yaml
charts/sn-platform/Chart.yaml
charts/sn-platform/values.yaml

* Upgrade console to version 1.6

Upgrade console to version 1.6

---

charts/sn-console/templates/console/streamnative-console-statefulset.yaml
charts/sn-console/values.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/values.yaml

* Add global resource global read only option

Add global resource global read only option

---

charts/sn-console/Chart.yaml
charts/sn-console/values.yaml
charts/sn-platform/Chart.yaml
charts/sn-platform/values.yaml

* Support okta sso login
* Support global resource read-only for sn console

Update sn console version and upgrade sn platform version

---

charts/pulsar/templates/broker/_broker.tpl
charts/pulsar/templates/broker/broker-configmap.yaml
charts/pulsar/templates/broker/broker-statefulset.yaml
charts/pulsar/values.yaml

---
*Motivation*
Allow enabling the filesystem offloader with helm charts.
*Modifications*
Add filesystem offloader configurations in the pulsar charts.

Add filesystem offloader configurations

---

charts/sn-console/Chart.yaml
charts/sn-console/values.yaml
charts/sn-platform/Chart.yaml
charts/sn-platform/values.yaml

* Upgrade sn console version to 1.8
* Upgrade sn platform version to 1.2.21

Fixed sn console version

---

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

To support resources.limits config for broker, bookie, proxy, zk crd.

feat(charts): support resource limits config for pulsar crds

---

charts/pulsar/templates/detector/pulsar-detector-statefulset.yaml

https://github.com/streamnative/managed-clusters/issues/529

Add auth parameter for detector.

---

charts/sn-platform/values.yaml

Update comment about field allowedClusters

---

charts/sn-console/Chart.yaml
charts/sn-console/values.yaml
charts/sn-platform/Chart.yaml
charts/sn-platform/values.yaml

Upgrade console version
* Fixed log4jshell issue
* Fixed super service account expire issue
* Fixed namespaces number

Upgrade console and chart version

---

charts/sn-platform/Chart.yaml
charts/sn-platform/values.yaml

* Upgrade pulsar and chart version

Upgrade pulsar and chart version

---

charts/sn-platform/Chart.yaml
charts/sn-platform/values.yaml

* Revert chanage 
* Release chart 1.2.26

Revert latest change for chart

---

charts/sn-platform/Chart.yaml
charts/sn-platform/values.yaml

After the image 2.8.1.30 was successfully released, I re-upgraded it to version 2.8.1.30.
* Reupgrade sn platform pulsar version to 2.8.1.30
* Upgrade chart version to 1.2.27

Reupgrade sn platform to 2.8.1.30

---

charts/sn-platform/conf/broker/connectors.yaml

* Update connector configuration

Update connector configuration

---

charts/pulsar/Chart.yaml
charts/pulsar/templates/function-worker/_function_worker.tpl
charts/sn-platform/Chart.yaml
charts/sn-platform/templates/function-worker/_function_worker.tpl
charts/sn-platform/values.yaml

Use to use FQDN as pulsar broker/web service url for dedicated function worker.

Update pulsar broker/web service url for dedicated function worker.

---

charts/sn-console/templates/console/streamnative-console-statefulset.yaml

Update console sts file

---

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

* Support custom labels for pulsar zk, and bookie cluster

Support custom labels for pulsar zk, and bookie cluster

---

charts/pulsar/Chart.yaml
charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml
charts/sn-platform/Chart.yaml
charts/sn-platform/templates/broker/function-worker-configfile-configmap.yaml

Dedicated function worker only enable auth and broker client auth when broker enabled auth.

---

charts/sn-console/templates/console/streamnative-console-ingress.yaml
charts/sn-console/values.yaml

(cherry picked from commit 53ff0d7a7962a81bd73881c727fcb6ab133ac6b9)

Support ingress configuration for sn console

---

charts/sn-platform/templates/vault/vault-initialize-public-key.yaml

* Add a new vault job for init public key file

Add a new vault job for init public key file

---

charts/pulsar-operator/templates/_helpers.tpl
charts/pulsar-operator/templates/bookkeeper-operator/operator.yaml
charts/pulsar-operator/templates/pulsar-operator/operator.yaml
charts/pulsar-operator/templates/zookeeper-operator/operator.yaml
charts/pulsar-operator/values.yaml

[pulsar-operator] Fix imagePullSecrets issue that it hasn't been used in deployment

---

charts/pulsar/templates/detector/pulsar-detector-statefulset.yaml
charts/pulsar/values.yaml
charts/sn-platform/templates/detector/pulsar-detector-statefulset.yaml
charts/sn-platform/values.yaml

Allow setting nodeSelector and tolerations for pulsar-detector pod.

---

charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
charts/sn-platform/templates/broker/_broker.tpl
charts/sn-platform/templates/proxy/_proxy.tpl
charts/sn-platform/templates/zookeeper/_zookeeper.tpl

Update container name to the name used by operator if operator is enabled.
Resolve: https://github.com/streamnative/charts/issues/483

Fix Datadog annotation for Autodiscovery.

---

charts/sn-platform/templates/vault/vault-initialize.yaml
charts/sn-platform/templates/vault/vault-statefulset.yaml

Support imagepullsecrets in Vault pod and Vault init job.

---

charts/sn-platform/Chart.yaml

[Release] Release sn-platform 1.2.33

---

charts/sn-platform/templates/broker/broker-cluster.yaml

Fixes https://github.com/streamnative/charts/issues/284
Current KoP svc address uses `{{ .Values.namespace }}` so it will be wrong if users don't set the `namespace` in Chart values.
Replace the `{{ .Values.namespace }}` with the `{{ template "pulsar.namespace" . }}`
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

fix(charts): replace the namespace in kop svc with a template

---

.github/PULL_REQUEST_TEMPLATE.md

Fix pull request template doc to match the documentbot regex
Add `` to doc label

[workflow] Fix pull request template doc

---

.ci/clusters/values-datadog.yaml
.github/workflows/sn-platform.yml
charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
charts/sn-platform/templates/broker/_broker.tpl
charts/sn-platform/templates/proxy/_proxy.tpl
charts/sn-platform/templates/zookeeper/_zookeeper.tpl

Fix datadog annotation for bk/zk/broker/proxy
Datadog annotation annotation key is missing 
It's a bug fix.

Fix datadog annotation for bk/zk/broker/proxy

---

charts/sn-platform/Chart.yaml

* Upgrade sn-platform to 1.2.34
* Update Chart.yaml file
*(or)*
*(or)*
*(example:)*
Some bug fixes

Update sn platform version to 1.2.34

---

charts/sn-platform/values.yaml

Fixes #<xyz>
Exception:
```
2022/03/01 06:36:35 [ERR] Error flushing to statsd! Err: write udp 127.0.0.1:54382->127.0.0.1:9125: write: connection refused
2022/03/01 06:36:40 [ERR] Error flushing to statsd! Err: write udp 127.0.0.1:54163->127.0.0.1:9125: write: connection refused
2022/03/01 06:36:45 [ERR] Error flushing to statsd! Err: write udp 127.0.0.1:35834->127.0.0.1:9125: write: connection refused
2022/03/01 06:36:50 [ERR] Error flushing to statsd! Err: write udp 127.0.0.1:43058->127.0.0.1:9125: write: connection refused
2022/03/01 06:36:55 [ERR] Error flushing to statsd! Err: write udp 127.0.0.1:38946->127.0.0.1:9125: write: connection refused …
```

Update telemetry default value

---

charts/sn-console/Chart.yaml
charts/sn-platform/Chart.yaml

* Upgrade sn-platform to 1.2.35, upgrade sn-console to 1.10

Upgrade sn platform and sn console version

---

charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/values.yaml

Fixes #513 
The function of kop tls will not working well  without kop configuration item `kopSslTruststoreLocation` 
Add `trustCertsEnabled` to set kop configuration item kopSslTruststoreLocation

Add `trustCertsEnabled` to set `kop.tls` configuration item `kopSslTruststoreLocation`

---

charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml
charts/pulsar/templates/presto/presto-coordinator-configmap.yaml
charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml
charts/pulsar/templates/presto/presto-worker-configmap.yaml
charts/pulsar/templates/presto/presto-worker-statefulset.yaml
charts/pulsar/templates/tls/tls-certs-internal.yaml
charts/pulsar/templates/zookeeper/_zookeeper.tpl

Necessary changes to support tls for presto.
Generate and mount tls cert for presto.

Add presto tls related resources.

---

charts/sn-platform/conf/streamnative_console/init_instance.py
charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-service.yaml

Fixed #522 
*(or)*
*(or)*
*(example:)*
Check …

Expose console backend port

---

charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/values.yaml

Update value example file for support offload configuration

---

charts/sn-platform/README.md

Add doc for configuring LB tls termination.
Add doc.
This is a doc pr.

Add doc for configuring LB tls termination.

---

charts/sn-platform/Chart.yaml

Bump sn-platform chart version to 1.2.37
Bump sn-platform chart version to 1.2.37
*(or)*
*(or)*
*(example:)*

release: bump sn-platform chart version to 1.2.37

---

charts/sn-platform/Chart.yaml

release: bump sn-platform chart version to 1.2.38
release: bump sn-platform chart version to 1.2.38
*(or)*
*(or)*
*(example:)*

release: bump sn-platform chart version to 1.2.38

---

charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
Master Issue: https://github.com/streamnative/charts/issues/539
* Users want to run the SN platform on Azure AKS and enable tiered storage to use the Azure Blob store
*(or)*
*(or)*
*(example:)*
- *Extended integration test …

Feature support configuration azure blob offload

---

charts/sn-platform/values.yaml

sn-platform values includes some images from vault-operator, pulsar-operator, function-mesh-operator and cert-manager, which not used in sn-palform chart.  To remove them to avoid confusion. 
Remove images not used in sn-palform chart. 
*(or)*
*(or)*
*(example:)*
(If you need help on updating …

fix(charts): remove needless images on sn-platform values

---

charts/sn-platform/templates/detector/pulsar-detector-statefulset.yaml
charts/sn-platform/templates/vault/vault-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #(https://github.com/streamnative/charts/issues/537)
Support additional annotation on vault and pulsar_detector.
Add additional annotations for detector and vault.
Fix vault persistence spec.

Support additional annotation on vault and pulsar_detector.

---

charts/sn-platform/templates/broker/_broker.tpl
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/broker/broker-configmap-functionmesh.yaml
charts/sn-platform/values.yaml

In order to install multiple releases in the same namespace, add support for the config map name of builtin connectors with release name as a prefix
Add support for the config map name of builtin connectors with release name as a prefix

Support the configmap name of builtin connectors with release name as a prefix

---

charts/sn-platform/README.md

Fixes #538 
Add doc for installing multiple pulsar cluster in one k8s
Add doc

Add doc for installing multiple pulsar cluster in one k8s

---

charts/sn-platform/Chart.yaml

Bump sn-platform chart to 1.3.0
Bump sn-platform chart to 1.3.0
*(or)*
*(or)*
*(example:)*

release: bump sn-platform chart to 1.3.0

---

charts/pulsar/Chart.yaml

Bump pulsar chart to 2.8.5
Bump pulsar chart to 2.8.5
*(or)*
*(or)*
*(example:)*

release: bump chart pulsar 2.8.5

---

.ci/release.sh
.github/workflows/release.yml

To support SN branch versioning to release
https://streamnative.slab.com/posts/private-cloud-release-bsvvocwq
Release workflow and release script

[CI] Support SN branch versioning to release

---

charts/sn-platform/values.yaml

Exception:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/pulsar/lib/org.apache.logging.log4j-log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/pulsar/lib/pulsar-package-storage-cloud-2.9.2.2-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[0.546s][info ][verification            ] locals: { 'org/apache/logging/log4j/spi/AbstractLogger', 'org/apache/logging/log4j/Level', 'java/lang/String' }
[0.546s][info ][verification            ] stack: { 'org/apache/logging/log4j/spi/AbstractLogger', 'java/lang/String', 'org/apache/logging/log4j/Level', null, 'java/lang/String', null } …
```

Remove unnecessary jvm parameters

---

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml

Fixes https://github.com/streamnative/charts/issues/577
Currently we can't apply custom affinity rule and default podAntiAffinity rule at the same tie.
Update template so we can apply them together.

Fix affinity rule.

---

charts/sn-platform/Chart.yaml

Bump sn-platform chart to 1.3.1
Bump sn-platform chart to 1.3.1
*(or)*
*(or)*
*(example:)*

release: bump sn-platform chart to 1.3.1

---

charts/sn-platform/Chart.yaml

Reverts streamnative/charts#587

Revert "release: bump sn-platform chart to 1.3.1"

---

README.md

Add release workflow document

---

charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml

Jvmoptions in PulsarBroker and PulsarProxy was marked as required while it should be optional.
Update pulsar operator crds.

Update pulsar operator crds.

---

charts/sn-console/values.yaml
charts/sn-platform/values.yaml

* Upgrade console image for fixed some security issue
* Update image for support pure oauth2 login
*(or)*
*(or)*
*(example:)*

Update sn platform console image

---

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes # https://github.com/streamnative/charts/issues/599
Master Issue: #599 
* Support configure numVolumes and numDirsPerVolume
*(or)*
*(or)*
*(example:)*
Check the box …

Add numVolumes and numDirsPerVolume for helm

---

charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/values.yaml

Resolve #559 
Add support for mop
Add `mop` configurations in the broker part.

[sn-platform] Add support for mop

---

charts/sn-platform/templates/vault/vault-initialize.yaml

Fixes https://github.com/streamnative/charts/issues/621

[sn-platform] fix: metadata of vault-initialize

---

charts/sn-platform/Chart.yaml

Reverts streamnative/charts#633

Revert "Bump sn-platform chart version to 1.4.0"

---

charts/pulsar/values.yaml

Bump image to 2.9.2.12
Bump image to 2.9.2.12
*(or)*
*(or)*
*(example:)*

[pulsar]: upgrade components images in pulsar chart

---

charts/pulsar/templates/broker/broker-cluster-role-binding.yaml
charts/pulsar/templates/broker/broker-configmap.yaml
charts/pulsar/templates/broker/function-mesh-configmap.yaml
charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml
charts/pulsar/values.yaml

Fixes https://github.com/streamnative/charts/issues/576
Allow charts configure Function Mesh to run function. (One prerequisite is the Cluster must installed FunctionMesh CRD and operator first.)
With this change, turn on function mesh in cluster should be as easy as setting in the `values.yaml` file:
```
functions:
functionMesh: true
```
- add `functionMesh` switch under `functions` section
- brokerCluster role get permissions to process FunctionMesh CRDs
- broker Configmap enable package service
- additional function mesh configmap for PulsarCluster address
- function worker config file with …

add function mesh teamples

---

charts/pulsar/templates/broker/_broker.tpl
charts/pulsar/templates/proxy/_proxy.tpl
charts/sn-platform/templates/broker/_broker.tpl
charts/sn-platform/templates/proxy/_proxy.tpl

In the most recent datadog client, native suport for Pulsar has been
added.
This change supports using the new annotations to use the native check.
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
- …

Add support for using new datadog check

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Update operator version for support use pod ip as advertised address

---

charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml

Fixes #<xyz>
function mesh configs need to be indented correctly to be effective
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

indent the function mesh config

---

charts/sn-platform/templates/toolset/_toolset.tpl
charts/sn-platform/templates/toolset/toolset-configmap.yaml
charts/sn-platform/templates/toolset/toolset-statefulset.yaml

Fixes #593 
Users can use `pulsarctl` directly in `toolset` pod without additional configuration work.
1. Populating pulsarctl config file
2. Mounting config file to toolset pod 
```
➜  k exec snp-sn-platform-toolset-0 -- pulsarctl tenants list
+-------------+
| TENANT NAME |
+-------------+
| public      |
| pulsar      |
| sn          |
+-------------+
```

feat: configure pulsarctl in toolset pod

---

charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml

Update pulsar-operator crds for version v0.10.2

Update pulsar-operator crds for version v0.10.2

---

charts/pulsar-operator/templates/bookkeeper-operator/rbac.yaml
charts/pulsar-operator/templates/pulsar-operator/rbac.yaml
charts/pulsar-operator/templates/zookeeper-operator/rbac.yaml

Fixes https://github.com/streamnative/charts/issues/662
See https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-
Add the missing permission to allow operators to run on k8s with [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) plugin enabled.
*(or)*
*(or)*
*(example:)*
- …

[pulsar-operator] Add permissions to allow operators to update finalizers

---

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml

Fixes https://github.com/streamnative/charts/issues/670
Fix security context for zk/bk/broker/proxy
Fix security context for zk/bk/broker/proxy
*(or)*
*(or)*
*(example:)*

[sn-platform] Fix security context for zk/bk/broker/proxy

---

charts/sn-platform/templates/streamnative-console/streamnative-console-configmap.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml

Master Issue: https://github.com/streamnative/charts/issues/556
Along with another PR https://github.com/streamnative/charts/pull/646/files, sn-platform deployment idempotent  is guaranteed 
Related issue: https://github.com/streamnative/charts/issues/556

[sn-platform] feat: make sn-platform deployment idempotent

---

charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/toolset/toolset-statefulset.yaml
charts/sn-platform/templates/vault/vault-initialize-public-key.yaml
charts/sn-platform/templates/vault/vault-initialize.yaml
charts/sn-platform/values.yaml

Fixes #678 
We need to configure the `securityContext` to accommodate Kubernetes environments with different security requirements.
Added `securityContext` for below components:
- `streamnative-console-initialize.yaml`
- `streamnative-console-statefulset.yaml`
- `toolset-statefulset.yaml`
- `vault-initialize-public-key.yaml`
- `vault-initialize.yaml`
```yaml
vault:
securityContext:
runAsUser: 0
toolset:
securityContext:
runAsUser: 0
streamnative_console:
securityContext:
runAsUser: 0
```

Support securityContext for vault/toolset/console

---

charts/sn-platform/templates/zookeeper/zookeeper-backup-statefulset.yaml

Fixes #671 
Fix the installation failure when enabling the zookeeper backup
Update filename

Fix the configmap filename of zookeeper backup

---

charts/sn-platform/ci/disable-monitoring-values.yaml
charts/sn-platform/ci/disable-vault-values.yaml
charts/sn-platform/ci/enable-istio-values.yaml
charts/sn-platform/ci/enable-zookeeper-backup.yaml

Resolve #596 
Improve the validation of chart issues
- Add directory `ci` in sn-platform chart
- Add value files which have the suffix `-values.yaml` in  directory `ci`

Verify the sn-platform using lint with multiple profiles

---

charts/sn-platform/templates/_helpers.tpl

(cherry picked from commit a89a47de8c250470b496f46863d3bb5e4d5ce2f3)
Fixes #<xyz>
*(or)*
*(or)*
*(example:)* …

Fixed cherry pick gcOptions fixed

---

charts/sn-platform/templates/streamnative-console/_streamnative-console.tpl
charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-service-account.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/values.yaml

* Add a dedicated service account for the console
* Remove trailing errors.
* Revert the container security context.
* Remove duplicated service account annotations
Fixes #<xyz>
*(or)*
*(or)*
This change added tests and can be verified as …

cherry-pick: Add a dedicated service account for the console (#688)

---

charts/sn-platform/templates/toolset/_toolset.tpl
charts/sn-platform/templates/toolset/toolset-serviceaccount.yaml
charts/sn-platform/templates/toolset/toolset-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #689 
The toolset use the `default` SA, which will bring security issues. So adding a dedicated service account for the toolset
Create a new `ServiceAccount` and use it in toolset sts.
*(or)*
*(or)*
*(example:)*

Add a dedicated service account for the toolset

---

charts/pulsar-operator/values.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/broker/broker-role-binding.yaml
charts/sn-platform/values.yaml

Fixes #575
Add necessary config to use function-mesh worker service
Function mesh worker service is transparent replacement of function service.

[sn-platform] Add necessary config to use function-mesh worker service

---

charts/sn-platform/templates/toolset/_toolset.tpl
charts/sn-platform/templates/toolset/toolset-configmap.yaml
charts/sn-platform/templates/toolset/toolset-serviceaccount.yaml
charts/sn-platform/templates/toolset/toolset-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

cherry-pick: #593 #689

---

charts/sn-platform/templates/openshift/_openshift.tpl
charts/sn-platform/templates/openshift/scc-role.yaml
charts/sn-platform/templates/openshift/scc-rolebinding.yaml
charts/sn-platform/templates/openshift/scc.yaml
charts/sn-platform/values.yaml

Fixes #696 
To create a custom SCC to allow the sn-platform to be successfully deployed on OpenShift.
Added a new value `openshift.enabled`  to control generating SCC and related role/rolebinding.
```
openshift:
enabled: true
```

Support SecurityContextConstraints for deploying on OpenShift

---

charts/sn-platform/templates/vault/vault-initialize.yaml

Only exec vault init job on stage `post-install`

fix: vault init job optimize, just exec on post-install

---

charts/pulsar/templates/proxy/proxy-configmap.yaml

It seems like we add duplicate keys in proxy config map. This can cause
issues.
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large …

Fix duplicate keys in proxy CM

---

charts/sn-platform/templates/openshift/scc.yaml

Fix scc issue .
Remove groups `system:authenticated` from scc.

Remove groups from scc

---

charts/sn-platform/templates/proxy/proxy-cluster.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: add `ServiceAccount` to pulsar proxy

---

charts/sn-platform/templates/proxy/proxy-cluster.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

cherry-pick: #705

---

charts/sn-platform/templates/broker/broker-authorizationpolicy.yaml

Resolve #648 
Expose mop on the istio gateway.
Allow the port `5684` in authorization policy of the broker.

Expose mop on the istio gateway

---

charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml
charts/pulsar/values.yaml

Fixes #<xyz>
Add the SA configuration option into template for function mesh
The generate file would be:
```
1780     functionsWorkerServiceNarPackage: "/pulsar/lib/mesh-worker-service.nar"
1781     functionsWorkerServiceCustomConfigs: |
1782       jobNamespace: "pulsar"
1783       defaultServiceAccountName: "pulsar-function-worker"
1784       extraDependenciesDir: "/pulsar/lib"
1785       functionEnabled: "true"
1786       sinkEnabled: "true"
1787       sourceEnabled: "true"
1788       uploadEnabled: "true"
1789       functionRunnerImages:
1790 …
```

allow configure function mesh service account

---

charts/sn-platform/values.yaml

bump snp images from 2.9.2.9 to 2.9.2.17
bump snp images from 2.9.2.9 to 2.9.2.17
*(or)*
*(or)*
*(example:)*

[sn-platform]: bump snp images from 2.9.2.9 to 2.9.2.17

---

charts/pulsar/templates/broker/_broker.tpl
charts/pulsar/templates/broker/broker-statefulset.yaml
charts/pulsar/values.yaml

Fixes #<xyz>
Configure the broker to mount built-in connector configmap
*(or)*
*(or)*
*(example:)*
(If you …

let broker mount bulitin connector configmap

---

charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/values.yaml

Support mounting additional volumes to broker.

Support mounting additional volumes to broker.

---

charts/sn-platform/templates/zookeeper/_zookeeper.tpl
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml

Fix ZooKeeperCluster storageClassName for dataLog.

Fix ZooKeeperCluster storageClassName for dataLog.

---

charts/pulsar/templates/prometheus/prometheus-configmap.yaml
charts/pulsar/values.yaml
charts/sn-platform/templates/prometheus/prometheus-configmap.yaml
charts/sn-platform/values.yaml

Backport https://github.com/streamnative/charts/pull/525
*(or)*
*(or)*
*(example:)*

[charts/pulsar][backport][v2.7.0] Add support for additional scrape rules in prom (#525)

---

charts/sn-console/templates/console/streamnative-console-statefulset.yaml
charts/sn-console/values.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Support enable and disable connector flink sql on console

---

charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix an issue with a bad yaml file

---

charts/sn-platform/conf/broker/connectors.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Update connector data, sync with cloud api server

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/values.yaml

- Upgrade images version to v0.11.1
- Upgrade PulsarBroker CRD

Upgrade pulsar-operator to v0.11.1

---

charts/sn-platform/templates/broker/broker-authorizationpolicy.yaml

[sn-platform]Fix broker AuthorizationPolicy template

---

charts/sn-platform-vault/templates/_vault.tpl
charts/sn-platform-vault/templates/vault-initialize.yaml

Update Vault init job.
*(or)*
*(or)*
*(example:)*

Update Vault init job.

---

charts/sn-platform/Chart.yaml
charts/sn-platform/conf/vault/init_vault_streamnative_console/startup.sh
charts/sn-platform/templates/vault/vault-initialize.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Support custom init username and password

---

charts/sn-platform/templates/broker/_broker.tpl
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/detector/_detector.tpl
charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/tls/tls-certs-internal.yaml

Resolves #735 
Support broker generic tls
Support config broker tls with PulsarBroker `.spec.tls`

[sn-platform]Support broker generic tls

---

charts/sn-platform/values.yaml

Fixes #<xyz>
Upgrade images version to fix vulnerabilities
Upgrade images version to fix vulnerabilities
*(or)*
*(or)*
*(example:)*
Check the …

fix(sn-platform): upgrade images version to fix vulnerabilities

---

charts/sn-platform/values.yaml

Fixes #698 
imagePuller has been removed from sn-platform template, so we can remove related legacy configs in values. 
*(or)*
*(or)*
*(example:)*
- *Extended …

fix(sn-platform): remove legacy configs of imagePuller

---

charts/sn-platform/templates/_helpers.tpl
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/detector/pulsar-detector-authorizationpolicy.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
charts/sn-platform/templates/istio/default-peerauthentication.yaml
charts/sn-platform/templates/node-exporter/node-exporter.yaml
charts/sn-platform/templates/presto/presto-coordinator-statefulset.yaml
charts/sn-platform/templates/presto/presto-worker-statefulset.yaml
charts/sn-platform/templates/prometheus/prometheus-configmap.yaml
charts/sn-platform/templates/vault/vault-statefulset.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml

Fixes #731 
1. Add default strict PeerAuthentication
2. Disable Istio metrics merging feature

[sn-platform] Fix prometheus scrape failed in Istio mode

---

charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/values.yaml

Master Issue: #627 
Remove components.aop flag.
Remove components.aop flag.

Remove components.aop from manifests

---

charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform/templates/vault/vault-initialize.yaml

https://github.com/streamnative/charts/issues/746

fix: remove helm hook in sn-platform chart about vault and console

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/templates/pulsar-operator/operator.yaml
charts/pulsar-operator/values.yaml

- upgrade pulsar-operator version to v0.11.5
- expose `.Values.puslar.extraEnv`

[pulsar-operator] upgrade operators

---

.github/workflows/sn-platform-stack.yml
.github/workflows/sn-platform-vault.yml
charts/sn-platform-stack/Chart.yaml

Fixes #763 
Fix the action failure.
- Update the dependencies registry to `https://charts.streamnative.io` for `sn-platform`.
- Fix action name.

Fix sn-platform-stack basic template action failure

---

charts/sn-platform/templates/prometheus/prometheus-configmap.yaml

Fixes #<xyz>
https://github.com/streamnative/charts/pull/742 made some changes on Prometheus configmap template, and the change on `relabel_configs` location will lead config problem if Istio is not enabled. And Prometheus Pod will fail to start.
Fix the issue made in https://github.com/streamnative/charts/pull/742/files#diff-9f6a1bd46a8fd81e6e8a93ff40c576f5b60f25d4d1230875c740751abbdf9db2
*(or)*
This change is already …

fix(sn-platform): Prometheus configmap template issue

---

charts/pulsar/templates/proxy/proxy-service-ingress.yaml
charts/pulsar/values.yaml

* [Feat][Pulsar] Allow customizing Proxy ingress svc https port.
Allow customizing Proxy ingress svc https port so it's not tie to https container port.

[Feat][Pulsar] Allow customizing Proxy ingress svc https port. (#771)

---

charts/pulsar/templates/proxy/proxy-service.yaml
charts/pulsar/values.yaml

Merge from master.
* Update Proxy service port mapping.
Follow up for https://github.com/streamnative/charts/pull/771
Also upgading Proxy service to able to customize https port mapping.

Update Proxy service port mapping. (#778)

---

charts/pulsar/values.yaml
charts/sn-console/templates/console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Remove flink sql flag from chart

---

.github/workflows/sn-platform-detector.yml
charts/sn-platform-common/templates/_commmon.tpl
charts/sn-platform-detector/Chart.yaml
charts/sn-platform-detector/templates/_detector.tpl
charts/sn-platform-detector/templates/pulsar-detector-deployment.yaml
charts/sn-platform-detector/templates/pulsar-detector-pdb.yaml
charts/sn-platform-detector/templates/pulsar-detector-service-account.yaml
charts/sn-platform-detector/templates/pulsar-detector-service.yaml
charts/sn-platform-detector/values.yaml
charts/sn-platform-stack/Chart.yaml
charts/sn-platform-stack/values.yaml
charts/sn-platform-vault/Chart.yaml

resolves #460
Create dedicated chart for Pulsar detector.
Create new chart sn-platform-detector to hold Pulsar detector component.
Make sn-platform-stack to use `sn-platform-detector` chart.

Create chart for Pulsar detector.

---

charts/sn-platform/templates/prometheus/prometheus-configmap.yaml
charts/sn-platform/templates/vault/vault-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #700 
Support expose vault metrics by bank-vaults ports https://github.com/banzaicloud/bank-vaults/blob/main/cmd/bank-vaults/metrics.go#L117
Support expose vault metrics
*(or)*
*(or)*
*(example:)*
- …

feat(sn-platform): support vault metrics expose

---

charts/pulsar/templates/toolset/_toolset.tpl

cherry-pick https://github.com/streamnative/charts/pull/782 to v1.3.3

[pulsar] Support proxy service port mapping in toolset (#782)

---

charts/sn-platform/templates/broker/broker-cluster.yaml

Fixes #<xyz>
Kafka client above the 3.1.1 will got the error of 
```
2022-06-21T08:19:01,725+0000 [pulsar-io-4-1] ERROR io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - error while handle command:
java.lang.IllegalArgumentException: Broker has disabled transaction coordinator, please enable it before using transaction.
```
When producing to the KoP
Add the config of `kafkaTransactionCoordinatorEnabled`
*(or)*
This …

feat(sn-platform): Add kop TransactionCoordinatorEnabled config support

---

charts/sn-platform/values.yaml

Fixes #<xyz>
Remove deprecated image configs in sn-platform chart.
Remove deprecated image configs in sn-platform chart.
*(or)*
*(or)*
*(example:)*
(If …

[sn-platform]: Remove deprecated image configs

---

license_test.go
test-values/sn-platform/1.3/normal.yaml
test-values/sn-platform/1.4/normal.yaml
test-values/sn-platform/1.5/normal.yaml

Add test value files for long-running environment.
Add test value files for long-running environment.

Add test value files for long-running test env

---

charts/sn-platform/values.yaml

Fixes #<xyz>
bump sn-platform images from `2.9.2.17` to `2.9.2.20`
bump sn-platform images from `2.9.2.17` to `2.9.2.20`
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after broker …

feat(sn-platform): bump sn-platform images from 2.9.2.17 to 2.9.2.20

---

.github/workflows/long_running_tests.yml
.github/workflows/pulsar.yml
.github/workflows/pulsar_bk_tls.yml
.github/workflows/pulsar_broker_ip.yml
.github/workflows/pulsar_broker_tls.yml
.github/workflows/pulsar_function.yml
.github/workflows/pulsar_image.yml
.github/workflows/pulsar_jwt_asymmetric.yml
.github/workflows/pulsar_jwt_symmetric.yml
.github/workflows/pulsar_sa_disabled.yml
.github/workflows/pulsar_service_account.yml
.github/workflows/pulsar_tls.yml
.github/workflows/pulsar_upgrade.yml
.github/workflows/pulsar_zk_tls.yml
.github/workflows/pulsar_zkbk_tls.yml

Master Issue: #772 
Trigger the pulsar workflow only when pulsar-related workflows are updated.
Update the path regular expression.

Trigger the pulsar workflow only when pulsar-related workflows are updated

---

charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/vault/vault-clear-resource.yaml

Fixes #797 
Add missing imagePullSecrets for sn-platform console and vault.
Add `imagePullSecrets` for below resources by reusing the `global.imagePullSecrets` value:
- streamnative-console-initialize.yaml
- streamnative-console-statefulset.yaml
- vault-clear-resource.yaml
*(example:)*

[sn-platform] Add missing imagePullSecrets

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
charts/pulsar-operator/values.yaml
charts/sn-platform/templates/broker/broker-authorizationpolicy.yaml

Fixes https://github.com/streamnative/charts/issues/776
Support AoP in Istio.

Support AoP in Istio.

---

charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
charts/sn-platform/values.yaml

Values:
```yaml
functions:
nodeSelector:
node: pulsar
tolerations:
- effect: NoSchedule
key: dedicated
operator: Equal
value: pulsar
```
Before:
```bash
Error: YAML parse error on sn-platform/templates/function-worker/function-worker-statefulset.yaml: error converting YAML to JSON: yaml: line 61: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 61: did not find expected key
```
After:
```yaml
nodeSelector:
node: pulsar
tolerations:
- effect: NoSchedule
key: dedicated
operator: Equal
value: pulsar
```

Fix function-worker template

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/values.yaml

Update operator to v0.12.0

---

charts/sn-console/Chart.yaml
charts/sn-console/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Update console version to 1.13.0 for fixed security issue

---

charts/sn-platform-vault/scripts/Dockerfile
charts/sn-platform-vault/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Add Dockerfile, update image version, fixed security issue

---

charts/sn-platform/templates/prometheus/prometheus-configmap.yaml

Fixes #<xyz>
Ignore istio,console for prometheus scrape when istio enabled
Ignore istio,console for prometheus scrape when istio enabled
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

feat(sn-platform): Ignore istio,console for prometheus when istio enabled

---

charts/pulsar/templates/tls/tls-cert-internal-issuer.yaml
charts/pulsar/templates/tls/tls-cert-public-issuer.yaml
charts/pulsar/templates/tls/tls-certs-internal.yaml
charts/pulsar/templates/tls/tls-certs-public.yaml
charts/pulsar/values.yaml

Update to use cert-manager v1 version.
*(or)*
*(or)*
*(example:)*

[Pulsar]Update to use cert-manager v1 version.

---

charts/sn-platform/templates/openshift/scc.yaml

Fixes #799 
`IPC_LOCK` and `SETFCAP` is required by vault. [See vault operator](https://github.com/banzaicloud/bank-vaults/blob/6315c06b1926e91170fdd707cfefdea0eead3cd7/operator/pkg/controller/vault/vault_controller.go#L1886)
- Remove `SETUID`, which is not required by any components
- Only set `IPC_LOCK` and `SETFCAP` when vault is enabled
This change has been verified n OpenShift.

Remove unused capability and set `allowedCapabilities` only when vault is enabled

---

.github/workflows/long_running_tests.yml

Fixes #812 
Update GKE cluster info to use a cluster `chart-tests-long-running` that in project `sncloud-test`
Update  GKE cluster info.

Update gke cluster info

---

charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml
charts/pulsar/templates/tls/tls-certs-internal.yaml

Fixes #815 
TLS for pulsar charts is broken
1. correct variable `.Values.tls.bookkeeper`
2. include required dns name when generate self signed cert
3. fix broken configmap template pulsar-functions-worker-configfile
bug fix

Fix tls related issue in pulsar charts:

---

charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes #810 
Support resources limits for init containers in sn-platform according to [Resource Management for Pods and Containers
](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
It should be noted that the resources strategy is different from regular containers as [quoted](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources) below:
>The highest of any particular resource request or limit defined on all init containers is the effective init request/limit. If any resource has no resource limit specified this is considered as the highest limit.
Added `<component>.initContainers.resources.limits`
```
<component>:
initContainers:
resources:
limits:
cpu: "0.1"
memory: 250MBi
``` …

[sn-platform] Support resources limits for init containers

---

examples/sn-platform/values-no-vault.yaml
examples/sn-platform/values-proxy-with-istio.yaml

Add some config sample of `sn-platform` chart
Add some config sample of `sn-platform` chart
*(or)*
*(or)*
*(example:)*

feat(sn-platform): add some usage example values

---

examples/sn-platform/values-broker-override-config.yaml
examples/sn-platform/values-proxy-with-ingress.yaml

Add more sn-platform chart usage examples
Add more sn-platform chart usage examples
*(or)*
*(or)*
*(example:)*

feat(sn-platform): add more sn-platform usage examples

---

charts/sn-platform/templates/_helpers.tpl
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
charts/sn-platform/templates/presto/presto-coordinator-statefulset.yaml
charts/sn-platform/templates/presto/presto-worker-statefulset.yaml
charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-backup-statefulset.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

This commit has two major changes:
1. It refactors affinity support to use a partial template to centralize
and simplify the affinity calculation
2. It adds support for zone affinity, this is useful for cases where a
user wants to ensure a cluster is spread across zones
Fixes #<xyz>
*(or)*
This change is already covered by …

Add support for zone anti_affinity, refactor affinity

---

charts/sn-platform/templates/presto/_presto.tpl
charts/sn-platform/templates/presto/presto-authrozationpolicy.yaml
charts/sn-platform/templates/presto/presto-destinationrule.yaml
charts/sn-platform/templates/presto/presto-gateway.yaml
charts/sn-platform/templates/presto/presto-service-ingress.yaml
charts/sn-platform/templates/presto/presto-serviceentry.yaml
charts/sn-platform/templates/presto/presto-virtualservice.yaml
charts/sn-platform/values.yaml

Resolves #825 
Support Presto under Istio mode
- AuthorizationPolicy for coordinator/worker
- DestinationRules for coordinator/worker
- ServiceEntry for coordinator/worker

[charts/sn-platform]: Make Presto compatible for Istio mode

---

charts/sn-platform/values.yaml

https://github.com/streamnative/cloud-manager/issues/1913

upgrade console image to v1.30.1

---

charts/sn-platform/templates/toolset/toolset-statefulset.yaml
charts/sn-platform/values.yaml

Resolves #837 
no need to install vim manually every time when using
Copy busybox/vim binary from the busybox initContainer.
Only command `vi` is available not `vim`, it's a limitation from busybox.
Get more commands usage guide with `busybox --help`

[sn-platform] Toolset add build-in busybox/vim command

---

charts/sn-platform/templates/alert-manager/alertmanager-deployment.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/templates/grafana/grafana-deployment.yaml
charts/sn-platform/templates/node-exporter/node-exporter.yaml
charts/sn-platform/templates/presto/presto-coordinator-statefulset.yaml
charts/sn-platform/templates/presto/presto-worker-statefulset.yaml
charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/toolset/toolset-statefulset.yaml
charts/sn-platform/values.yaml

There are some components missing the `labels` config, so this PR comes to add the missing `labels` config.
For these components, move the `labels` config location for better usage.
```
zk-cluster
bk-cluster
broker-cluster
proxy-cluster
```
For these components, add the `labels` config
```
autorecovery
detector
toolset
prometheus
grafana
node_exporter
streamnative_console
presto
alertmanager
```
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with …

feat(sn-platform): add missing labels config for several components

---

charts/sn-platform/templates/_helpers.tpl

CustomRules was breaking when being used.
This fixes the bug by having it match the if statement above

Fix bug with custom rules and new affinity logic

---

charts/sn-platform/templates/grafana/grafana-pvc.yaml
charts/sn-platform/templates/grafana/grafana-statefulset.yaml
charts/sn-platform/templates/prometheus/prometheus-pvc.yaml

Fixes #371 
Refactor the Grafana PVC and fix the issue 371
* Added the pvc template for Grafana.
* Updated the Grafana statefulset template.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for …

refactor(grafana): refactor grafana pvc template

---

charts/sn-platform/values.yaml

Bump `sn-platform` image version. 
Bump `sn-platform` image version. 
*(or)*
*(or)*
*(example:)*

bump(sn-platform): bump sn-platform image version

---

charts/sn-platform/values.yaml

Fixes #<xyz>
The default resource size of autorecovery is too small. 
Change the default resource size of autorecovery. 
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after broker …

fix(sn-platform): change the recovery default resource size

---

charts/sn-platform/values.yaml

Fixes #848
- Prevent confusing template error
- Add default value for external_domain_scheme

[sn-platform] Add default value for external_domain_scheme

---

charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml
charts/sn-platform/templates/zookeeper/zookeeper-backup-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #863 
- fix zookeeper backup sts template
- fix zookeeper backup sts initContainers
- improve function worker sts initContainers

[sn-platform] Fix zookeeper backup sts template

---

charts/sn-platform/templates/presto/presto-authrozationpolicy.yaml
charts/sn-platform/templates/presto/presto-coordinator-configmap.yaml
charts/sn-platform/templates/presto/presto-coordinator-statefulset.yaml
charts/sn-platform/templates/presto/presto-jmx-exporter-configmap.yaml
charts/sn-platform/templates/presto/presto-worker-configmap.yaml
charts/sn-platform/templates/presto/presto-worker-statefulset.yaml
charts/sn-platform/values.yaml

Resolves #846
- Export Presto metrics with JMX exporter
- Add JMX related JVM configuration and presto configuration
- Add JMX exporter container in presto coordinator and worker

[sn-platform] Export Presto metrics with JMX exporter

---

examples/sn-platform/external-zk.yaml
examples/sn-platform/zk-dynamic-reconfig.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
- *Extended …

Add some sn-platform usage examples related to zk

---

.github/workflows/sn-platform-detector.yml
.github/workflows/sn-platform-stack.yml
.github/workflows/sn-platform-vault.yml
.github/workflows/sn-platform.yml

Fixes #884 
- Bump azure/setup-helm action to v3
- Fix helm version to 3.7.2

[sn-platform] Fix helm error in lint-test jobs

---

charts/sn-platform/conf/broker/connectors.yaml

We have to add the new Debezium MS SQL Server source connector.
Added MS SQL source to the connectors.yaml

[charts] Add Debezium MS SQL Server source connector

---

charts/sn-platform/templates/presto/presto-coordinator-deployment.yaml
charts/sn-platform/templates/presto/presto-serviceentry.yaml
charts/sn-platform/templates/presto/presto-worker-configmap.yaml
charts/sn-platform/templates/presto/presto-worker-deployment.yaml
charts/sn-platform/values.yaml

Fixes #872 
Presto replicas should work as a ha cluster so statefulset is not suitable for this case cause it has order in pods.
*(or)*
*(or)*
*(example:)*
- …

feat(sn-platform): convert presto from sts to deployment

---

charts/sn-platform/templates/_helpers.tpl
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Reorganize auth module

---

charts/sn-platform/values.yaml

Fixes #874 
`sn-platform` keeps 2.9 pulsar image base for a long time, now we should upgrade to 2.10 image base. 
Also, upgrade some of the third-party components' images version. 
Image version bump. 
*(or)*
*(or)*
*(example:)*
- *Extended integration test …

[sn-platform]: bump pulsar image to 2.10 base

---

charts/sn-platform/conf/broker/connectors.yaml

We will add the new BigQuery connector.
Added BigQuery connector info to the connectors.yaml.
*(or)*
*(or)*
*(example:)*

[charts] Add the Google BigQuery connector

---

charts/sn-platform/values.yaml

Fixes #<xyz>
Temporary fix: we make the toolset run as root by default to avoid some permission issues. Will support toolset run as non-root in future release. 
set toolset run as root by default
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large …

fix(toolset): set toolset run as root by default

---

charts/sn-platform/values.yaml

Noticed that a lot of PRs have been affected by this bug recently.
Remove trailing spaces.

Fix trailing spaces reported by chart linter

---

charts/sn-platform/conf/broker/connectors.yaml

Fixes #<xyz>
Add debezium oracle source connector on sn-platform
Add debezium oracle source connector 
*(or)*
*(or)*
*(example:)*
Check the …

feat(connector): add debezium oracle source

---

charts/sn-platform/templates/_helpers.tpl
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml

Fixes #910 
- Added top-level condition `.Values.auth.enabled` and `.Values.components.vault`
This change has been verified with following values
```yaml
components:
vault: false
auth:
authentication:
enabled: false
authorization:
enabled: false
```

[sn-platform] Fix unable to start broker and proxy when auth and vault disabled

---

charts/sn-platform/values.yaml

Fixes #<xyz>
Enable topic level policies by default
Enable topic level policies by default
*(or)*
*(or)*
*(example:)*
Need …

feat(sn-platform): enable topic level policies by default

---

charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
charts/sn-platform/templates/broker/_broker.tpl
charts/sn-platform/templates/prometheus/_prometheus.tpl
charts/sn-platform/templates/proxy/_proxy.tpl
charts/sn-platform/templates/zookeeper/_zookeeper.tpl
charts/sn-platform/values.yaml

Fixes #<xyz>
`.Values.datadog.namespace` is an unwanted config for users. It can be replaced by the template of `pulsar.namespace`. 
Replace the `.Values.datadog.namespace` by `template "pulsar.namespace" `
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment …

BREAKING CHANGE(sn-platform): deprecate `.Values.datadog.namespace` config

---

charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml

related to: https://github.com/streamnative/pulsar-operators/pull/775
Add `insecureAuthEnabled` field in pulsarbroker

Add insecureAuthEnabled field

---

charts/sn-platform/values.yaml

Fixed #916 
*(or)*
*(or)*
*(example:)*
Check …

Fixed console init failed

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
charts/pulsar-operator/values.yaml

Fixes #<xyz>
Upgrade to v0.14.0

[pulsar-operator] Upgrade to v0.14.0

---

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes #930 
Add values for PulsarBroker, PulsarProxy, BookkeeperCluster, and ZookeeperCluster.
*(or)*
*(or)*
*(example:)*

Support to add custom annotations and labels for CR

---

charts/sn-platform/Chart.yaml

Fixes #934 
*(or)*
*(or)*
*(example:)*
- *Extended …

bump(sn-platform): bump sn-platform appVersion

---

charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Upgrade confluent kafka version

---

charts/sn-platform/README.md

charts.streamnative.io no longer carries functionmesh.
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
- *Extended …

update functionmesh repo location

---

charts/sn-platform/README.md

Readme line124
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after broker …

fix functionmesh repo

---

charts/sn-platform/templates/toolset/toolset-configmap.yaml

Fixes #933 
*(or)*
*(or)*
*(example:)*
- *Extended …

fix(toolset): fix proxy address in toolset configmap

---

charts/sn-platform/templates/broker/broker-cluster.yaml

fix broker secretRefs under Istio mode(proxy not exist)
correct `.Values.proxy.publicKeySecret` to `.Values.broker.publicKeySecret`

[sn-platform] Fix broker secretRefs

---

charts/sn-platform/README.md

[charts/sn-platform] Fix broken links

---

charts/sn-platform/values.yaml

upgrade console image to v1.14.7

---

charts/pulsar-operator/templates/bookkeeper-operator/operator_rbac.yaml
charts/pulsar-operator/templates/pulsar-operator/operator_rbac.yaml
charts/pulsar-operator/templates/zookeeper-operator/operator_rbac.yaml

Operators' role lacks the permission for resources `leases` in API group `coordination.k8s.io` when enabling the namespace  -scoped operator.
*(or)*
*(or)*
*(example:)*

Fix operators permission issue

---

examples/pulsar-operators/quick-start.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[pulsar operators]: add a operator quick-start example

---

charts/pulsar/templates/external-dns/external-dns.yaml
charts/pulsar/values.yaml
charts/sn-platform/templates/control-center/_control_center.tpl
charts/sn-platform/values.yaml

Fixes #965 
> k8s.gcr.io Image Registry Will Be Frozen From the 3rd of April 2023
Replace k8s.gcr.io with registry.k8s.io

Replace k8s.gcr.io with registry.k8s.io

---

charts/sn-platform/conf/broker/connectors.yaml

We will add the new Snowflake connector.
Add the Snowflake connector info to the connectors.yaml.
*(or)*
*(or)*
*(example:)*

Add snowflake connector

---

examples/pulsar-operators/aop.yaml
examples/pulsar-operators/kop.yaml
examples/pulsar-operators/mop.yaml
examples/pulsar-operators/olm-subscription.yaml
examples/pulsar-operators/proxy.yaml
examples/pulsar-operators/quick-start.yaml
examples/pulsar-operators/storage.yaml

Fixes #<xyz>
Added examples about how to provision & manage through Operator API
* olm install
* KoP
* AoP
* MoP
* enable Proxy
* config storage
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

[pulsar-operators]: add more examples to provision & manage through operator API

---

charts/pulsar-operator/Chart.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[pulsar operators] bump pulsar operators kube supported version

---

charts/pulsar-operator/README.md
charts/pulsar-operator/templates/NOTES.txt

Fixes #<xyz>
* add the license info on pulsar operators chart 
* add more resources on pulsar operators chart
* add output information after installing the pulsar operators
*(or)*
*(or)*
*(example:)*
- *Extended …

[pulsar operators]: update the chart README & add the operator installing output

---

charts/sn-platform/values.yaml

Fixes #<xyz>
Bump the `sn-platform` image version to 2.10.3.4 to avoid impact from this change https://github.com/apache/pulsar/pull/19455
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …

bump snp image version to 2.10.3.4

---

charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/values.yaml

Fixes #925 
Add chart config for Pulsar RestAPI
*(or)*
*(or)*
*(example:)*
(If you need help on updating …

feat: add Pulsar RestAPI config

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
charts/pulsar-operator/values.yaml

Upgrade pulsar-operator to v0.15.2

---

charts/sn-platform/Chart.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore(sn-platform): bump snp chart version to 1.9

---

charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
charts/sn-platform/templates/broker/_broker.tpl
charts/sn-platform/templates/prometheus/_prometheus.tpl
charts/sn-platform/templates/proxy/_proxy.tpl
charts/sn-platform/templates/zookeeper/_zookeeper.tpl
charts/sn-platform/values.yaml

Fixes #<xyz>
Fix several issues in sn-platform datadog templates:
* The default `datadog.namespace` should be a emptyString rather than empty map. Otherwise will get an overwrite warning from Helm.
* Add the missing quotation marks for datadog related templates
* Add the missing `prometheus.metrics` config in the values. 
*(or)*
*(or)*
This change …

fix(sn-platform): fix several issues in sn-platform datadog templates

---

examples/pulsar-operators/aop.yaml
examples/pulsar-operators/kop.yaml
examples/pulsar-operators/mop.yaml
examples/pulsar-operators/proxy.yaml
examples/pulsar-operators/quick-start.yaml
examples/pulsar-operators/storage.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: change default memory in the examples

---

charts/sn-platform/values.yaml

Fixes #<xyz>
Updated the image for vault, prometheus, node_exporter and alertmanager repo and version for CVE fix, refer the scan report on https://artifacthub.io/packages/helm/prometheus-community/prometheus and https://artifacthub.io/packages/helm/hashicorp/vault
*(or)*
*(or)*
*(example:)*
- …

[sn-platform]: update several images repo and version for CVE

---

charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform] upgrade console image verison to v1.14.8

---

charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

upgrade console image to v1.14.10

---

charts/pulsar-operator/Chart.yaml

Fixes #980 
Update the kubeVersion limitation fix for operators chart
*(or)*
*(or)*
*(example:)*
(If you need …

fix: kubeVersion limitation fix for operators chart

---

.ci/clusters/values-function.yaml
.ci/helm.sh
charts/pulsar/templates/zookeeper/zookeeper-configmap.yaml

Fixes #987
`NIOServerCnxnFactory` doesn't support SSL
Use `NettyServerCnxnFactory` when tls is enabled for zookeeper
*(or)*
*(or)*
*(example:)*
(If you …

[pulsar] fix: use NettyServerCnxnFactory for zookeeper if tls is enabled

---

charts/pulsar/templates/zookeeper/zookeeper-backup-statefulset.yaml

---
Fixes #<xyz>
Before the fixing, it will throw
` error converting YAML to JSON: yaml: line 84: did not find expected key`
*(or)*
*(or)*
*(example:)* …

Only add extra init container when it exists

---

charts/pulsar/templates/zookeeper/zookeeper-backup-statefulset.yaml

---
Fixes #<xyz>
*(or)*
*(or)*
*(example:)* …

Fix the backup pod never get ready because of zk status

---

examples/pulsar-operators/olm-subscription.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: update the olm default channel to alpha

---

charts/sn-platform/templates/vault/vault-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform]: add vault affinity config support

---

charts/sn-platform-security/templates/toolset/_toolset.tpl
charts/sn-platform-security/templates/toolset/toolset-configmap.yaml
charts/sn-platform-security/templates/toolset/toolset-statefulset.yaml
charts/sn-platform-security/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[security chart]: remove cp-kafka in toolset pod for security chart

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml

[pulsar-operator] Upgrade to v0.16.0

---

charts/sn-platform/templates/proxy/_proxy.tpl
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
Add the `authenticateMetricsEndpoint` config on PulsarProxy, which will be used for the control the metrics auth on Proxy. 
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …

[sn-platform][feat]: add authenticateMetricsEndpoint on Proxy

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform][sn-platform-slim]: bump grafana image version

---

charts/sn-platform-slim/README.md
charts/sn-platform/README.md

Fixes #<xyz>
Follow with https://github.com/streamnative/charts/pull/1015
*(or)*
*(or)*
*(example:)*
(If you …

chore(doc): update slim readme for Subscription Agreement

---

charts/pulsar-operator/Chart.yaml
charts/pulsar/Chart.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

update charts logo

---

charts/sn-platform-slim/templates/toolset/toolset-statefulset.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform-slim]fix: toolset pod duplicate volumeMounts config

---

charts/sn-platform-slim/templates/broker/broker-cluster.yaml
charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Update template render when jwt auth enabled

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform][slim]bump console image to v2.1.3

---

charts/pulsar-operator/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: upgrade operator image to v0.16.2

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: bump console to 2.1.4

---

charts/pulsar/requirements.yaml
charts/sn-platform/requirements.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform][pulsar]: fix ci issue on loki chart source link change

---

charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
charts/pulsar-operator/values.yaml

[pulsar-operator] Upgrade to v0.16.3

---

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform-slim/templates/broker/broker-cluster.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform][sn-platform-slim]: fix the .values.initialize unlinked with the Broker and BK CR config

---

charts/sn-platform-slim/templates/broker/broker-cluster-role-binding.yaml
charts/sn-platform-slim/templates/broker/broker-cluster.yaml
charts/sn-platform-slim/templates/function-worker/function-worker-cluster-role-binding.yaml
charts/sn-platform-slim/templates/function-worker/function-worker-role-binding.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/broker/broker-cluster-role-binding.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/function-worker/function-worker-cluster-role-binding.yaml
charts/sn-platform/templates/function-worker/function-worker-role-binding.yaml
charts/sn-platform/values.yaml
examples/sn-platform/values-function-mesh.yaml

Fixes #1023
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform] Make function mesh configurable

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
Fix busybox 1.35 CVEs:
* CVE-2022-28391: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-28391
* CVE-2022-30065: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-30065
*
Upgrade to use busybox 1.36.1
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end …

chore: upgrade busybox image to fix CVEs

---

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform][sn-platform-slim]: add the extraEnv support for bk and zk

---

examples/sn-platform/values-pulsar-3.0.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

add values examples for 3.0 support

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
* bump platform image to `2.10.4.3`
* bump console image to `v2.2.0`
*(or)*
*(or)*
*(example:)* …

[sn-platform][sn-platform-slim]: bump platform and console images

---

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform-slim/templates/toolset/toolset-statefulset.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/toolset/toolset-statefulset.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform][sn-platform-slim]: add annotation support on toolset and console sts

---

charts/sn-platform-slim/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml

Fixes #<xyz>
`PulsarBroker` doesn't allow empty value for `spec.config.function.customWorkerConfig`, so only pass it when it's not empty
Add if statement to the `broker.functionmesh.customWorkerConfig`
*(or)*
*(or)*
*(example:)*
- *Extended integration test …

[sn-platform][sn-platform-slim] Add if statement for customWorkerConfig

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
charts/pulsar-operator/values.yaml

Fixes #1039 
Release pulsar operator to v0.16.4
- Update crds
- Bump image version to v0.1.6.4
*(or)*
*(or)*
*(example:)*

Release pulsar operator to v0.16.4

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Add security context for private cloud console

---

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-initialize.yaml
charts/sn-platform-slim/values.yaml

[sn-platform-slim] Sync console securityContext changes

---

charts/sn-platform-slim/templates/toolset/_toolset.tpl
charts/sn-platform-slim/templates/toolset/toolset-statefulset.yaml
charts/sn-platform/templates/toolset/_toolset.tpl
charts/sn-platform/templates/toolset/toolset-statefulset.yaml

Fixes #1055
Resolves #876
Support rootless toolset

[sn-platform][sn-platform-slim] Fix pulsarctl config

---

examples/pulsar-operators/proxy.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Update proxy.yaml example

---

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform][sn-platform-slim]: add resources param to the console gateway

---

examples/app-of-apps.yaml
examples/argocd/charts/sn-pulsar/Chart.yaml
examples/argocd/charts/sn-pulsar/templates/pulsar-operator.yaml
examples/argocd/charts/sn-pulsar/templates/sn-platform.yaml
examples/argocd/charts/sn-pulsar/values.yaml
examples/argocd/values/pulsar-operator.yaml
examples/argocd/values/sn-platform.yaml

- Best practice for deploying sn-platform using ArgoCD
- Add Application chart contains pulsar-operator and sn-platform 
- Add Application to deploy the Application chart

[example] Deploy sn-platform using ArgoCD

---

charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Update pulsar broker, proxy, zk and bk crd

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

bump operator to 0.17

---

charts/pulsar-operator/templates/bookkeeper-operator/operator_rbac.yaml
charts/pulsar-operator/templates/pulsar-operator/operator_rbac.yaml
charts/pulsar-operator/templates/zookeeper-operator/operator_rbac.yaml

Fixes #1062 
Fix operator rbac permission issue when watching specific namespace.
Add the related resources to the rules of the role.
*(or)*
*(or)*
*(example:)*

fix: operator rbac when watching specific namespace

---

ct.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Update ct.yaml to remove function-mesh charts

---

examples/sn-platform/values-kube-state-metrics.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix the example

---

charts/pulsar-operator/templates/bookkeeper-operator/rbac.yaml
charts/pulsar-operator/templates/pulsar-operator/pulsar_broker_clusterrole.yaml
charts/pulsar-operator/templates/pulsar-operator/rbac.yaml
charts/pulsar-operator/templates/zookeeper-operator/rbac.yaml

Fixes https://github.com/streamnative/charts/issues/1076
When use multi-namespace, rbac template should split the string with comma.

[fix] split multi-namespace in rbac role template

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

bump pulsar version to 2.10.4.7

---

charts/sn-platform/conf/vault/init_vault_streamnative_console/startup.sh
charts/sn-platform/templates/vault/vault-initialize.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
```
customPayload:
superToken: "\\\"role\\\":[\\\"admin\\\"]|\\\"role2\\\":\\\"admin2\\\""
nonSuperToken: "\\\"role\\\":[\\\"admin\\\",{{identity.entity.aliases.MOUNT_ACCESSOR.metadata.role_name}}]"
```
*(or)*
*(or)*
This change …

Support custom token payload

---

charts/sn-platform/values.yaml

Fixes #1089 
*(or)*
*(or)*
*(example:)*
Check …

fix: replace the toolset kafka container image

---

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[sn-platform][sn-platform-slim]Upgrade private cloud console version

---

charts/sn-platform-slim/templates/broker/broker-cluster.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
1. remove the `managedLedgerOffloadDriver` config in values. 
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …

fix: update the offload config

---

examples/pulsar-operators/offload-aws-s3.yaml
examples/pulsar-operators/offload-azureblob.yaml
examples/pulsar-operators/offload-gcs.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

examples: add offload examples for pulsar operator

---

charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

upgrade operator to 0.17.6 and replace the registry address

---

examples/pulsar-operators/aop.yaml
examples/pulsar-operators/kop.yaml
examples/pulsar-operators/logConfig.yaml
examples/pulsar-operators/mop.yaml
examples/pulsar-operators/offload-aws-s3.yaml
examples/pulsar-operators/offload-azureblob.yaml
examples/pulsar-operators/offload-gcs.yaml
examples/pulsar-operators/proxy.yaml
examples/pulsar-operators/quick-start.yaml
examples/pulsar-operators/storage.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: update examples image version

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml
examples/sn-platform/values-kube-state-metrics.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: upgrade grafana image to 0.1.0

---

charts/sn-platform-slim/Chart.yaml
charts/sn-platform/Chart.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: bump chart version

---

examples/pulsar-operators/logConfig.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Update logConfig.yaml example

---

examples/pulsar-operators/proxy.yaml
examples/pulsar-operators/quick-start.yaml
examples/pulsar-operators/storage.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix yaml examples

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Upgrade private cloud console version

---

charts/sn-platform-slim/templates/prometheus/prometheus-configmap.yaml
charts/sn-platform-slim/templates/prometheus/prometheus-statefulset.yaml
charts/sn-platform-slim/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

support external_labels on slim chart

---

charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml

Fixes #1112 
*(or)*
*(or)*
*(example:)*
Check …

fix: detector missed the resources limit on server container

---

charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/values.yaml

Fixes #1114 
*(or)*
*(or)*
*(example:)*
Check …

feat: support extra configurions for the detector

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml
charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml
charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
charts/pulsar-operator/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: upgrade pulsar operator appVersion

---

charts/sn-platform-slim/templates/toolset/jwt-secret-init-job.yaml
charts/sn-platform/templates/toolset/jwt-secret-init-job.yaml

Add imagePullSecrets for jwt init job

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: bump pulsar image to 3.1

---

charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

feat: add extraArgs for detector to support tls-auth

---

charts/pulsar-operator/Chart.yaml
charts/pulsar-operator/templates/bookkeeper-operator/operator.yaml
charts/pulsar-operator/templates/pulsar-operator/operator.yaml
charts/pulsar-operator/templates/zookeeper-operator/operator.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: operator missing the namespace env

---

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: expose the zk and bk accessModes config in values

---

charts/sn-platform-slim/templates/bookkeeper/_autorecovery.tpl
charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/bookkeeper/_autorecovery.tpl
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

feat: add datadog annotations for autorecovery

---

charts/sn-platform/templates/_helpers.tpl

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Remove deprecated option

---

charts/sn-platform-slim/templates/control-center/_control_center.tpl
charts/sn-platform-slim/templates/control-center/control-center-ingress.yaml
charts/sn-platform-slim/templates/control-center/ingress-controller-deployment.yaml
charts/sn-platform-slim/templates/control-center/ingress-controller-rbac.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/control-center/_control_center.tpl
charts/sn-platform/templates/control-center/control-center-ingress.yaml
charts/sn-platform/templates/control-center/ingress-controller-deployment.yaml
charts/sn-platform/templates/control-center/ingress-controller-rbac.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: Ingress rbac and support ingressClass

---

charts/sn-platform-slim/templates/openshift/scc-rolebinding.yaml
charts/sn-platform-slim/templates/openshift/scc.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: scc template in slim chart

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: update default zk size to avoid oom

---

charts/pulsar/values.yaml
charts/sn-platform/values.yaml
examples/sn-platform/values-pulsar-3.0.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: remove zk forceSync jvm configuration

---

charts/pulsar-operator/Chart.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

update pulsar operator chart limitation

---

charts/pulsar-operator/templates/NOTES.txt

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

update pulsar-operator output note

---

charts/pulsar-operator/README.md

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

udpate the operator readme

---

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform-slim/templates/toolset/toolset-statefulset.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/toolset/toolset-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

feat: support podLabel and podAnnotation for toolset and console

---

charts/sn-platform-slim/conf/broker/connectors.yaml
charts/sn-platform/conf/broker/connectors.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: update default connectors version

---

ct.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: update the lint ci scope

---

charts/sn-platform-slim/templates/control-center/control-center-ingress.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/control-center/control-center-ingress.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: template ingress route rules

---

charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: update the console init setting

---

README.md

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

update chart repo readme

---

charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: detector template

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: upgrade console version to v2.3.5-rc.5

---

charts/sn-platform-slim/templates/prometheus/prometheus-configmap.yaml
charts/sn-platform/templates/prometheus/prometheus-configmap.yaml

Fixes #<xyz>
`kubernetes-nodes` and `kubernetes-cadvisor` scrape job will be disabled when istio enabled, we should remove the limitation
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …

Fix prom config when istio enabled

---

charts/sn-platform-slim/conf/broker/connectors.yaml
charts/sn-platform/conf/broker/connectors.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

add aws-eventbridge sink connector to private cloud

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

upgrade the dashboard image to 0.1.2

---

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Fixed non auth token for console login when non auth enabled

---

charts/sn-platform-slim/conf/broker/connectors.yaml
charts/sn-platform-slim/conf/broker/log4j2.yaml
charts/sn-platform-slim/templates/broker/broker-configmap-functionmesh.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/broker/broker-configmap-functionmesh.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

feat: support builtin connector repository configuration

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: upgrade console version

---

scripts/pulsar/generate_token.sh

The `base64` command on Alpine requires different arguments.
*(or)*
*(or)*
*(example:)*

Fixed base64 decode on Alpine based image

---

charts/sn-platform/templates/toolset/jwt-secret-init-job.yaml

Fixes #<xyz>
Apply https://github.com/streamnative/charts/pull/1175 to the sn-platform chart.
*(or)*
*(or)*
*(example:)*
Need to …

apply PR 1175 to sn-platform chart

---

charts/sn-platform-slim/templates/pulsar-coordinator/pulsar-coordinator.yaml
charts/sn-platform/templates/pulsar-coordinator/pulsar-coordinator.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: pulsar_coordinator template issue

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Fix console cves

---

charts/sn-platform-slim/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

upgrade console to v2.3.9

---

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform-slim/templates/broker/broker-cluster.yaml
charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml
charts/sn-platform-slim/templates/pulsar-coordinator/pulsar-coordinator.yaml
charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/pulsar-coordinator/pulsar-coordinator.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes https://github.com/streamnative/eng-support-tickets/issues/1945

Support to use coordinator to upgrade pulsar components

---

charts/sn-platform-slim/templates/toolset/jwt-secret-init-job.yaml
charts/sn-platform/templates/toolset/jwt-secret-init-job.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: securityContext template on jwt init job

---

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

add extra configuration for Console JWT auth

---

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml
charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: console kop service port issue

---

charts/sn-platform/templates/vault/vault-initialize-public-key.yaml
charts/sn-platform/templates/vault/vault-initialize.yaml
charts/sn-platform/templates/vault/vault-statefulset.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix vault job template

---

charts/sn-platform-slim/templates/broker/_broker.tpl
charts/sn-platform/templates/broker/_broker.tpl

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

support datadog kop consumer

---

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform-slim/templates/broker/broker-cluster.yaml
charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml
charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

feat: support pdb control

---

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: duplicate pdb fields in the template

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

chore: upgrade pulsar image tag to 3.3.3.3

---

charts/sn-platform/requirements.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: loki dependency on sn-platform

---

charts/sn-platform-slim/templates/broker/broker-cluster-role-binding.yaml
charts/sn-platform-slim/templates/broker/broker-role-binding.yaml
charts/sn-platform/templates/broker/broker-cluster-role-binding.yaml
charts/sn-platform/templates/broker/broker-role-binding.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

fix: add the missing connectorCatalog permission on Broker SA

---

charts/sn-platform-slim/templates/broker/_functions.tpl
charts/sn-platform-slim/templates/broker/broker-builtin-connectors.yaml
charts/sn-platform-slim/templates/broker/broker-cluster.yaml
charts/sn-platform-slim/templates/broker/broker-configmap-functionmesh.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/broker/_functions.tpl
charts/sn-platform/templates/broker/broker-builtin-connectors.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/broker/broker-configmap-functionmesh.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

feat: support ConnectorCatalog for builtinConnector

---

charts/sn-platform-slim/conf/toolset/log4j2.yaml
charts/sn-platform/conf/toolset/log4j2.yaml

log4j2 for toolset is not the same one with brokers. Change log level to ERROR.

Fix warning log

---

charts/sn-platform-slim/templates/control-center/control-center-ingress.yaml
charts/sn-platform/templates/control-center/control-center-ingress.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Update ingress class name

---

charts/sn-platform-slim/templates/pulsar-coordinator/pulsar-coordinator.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/pulsar-coordinator/pulsar-coordinator.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Support node selector and disable toolset

---

charts/sn-platform-slim/templates/_helpers.tpl
charts/sn-platform/templates/_helpers.tpl

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

temp: change the jwt auth token template

---

charts/sn-platform-slim/templates/bookkeeper/_autorecovery.tpl
charts/sn-platform-slim/templates/bookkeeper/_bookkeeper.tpl
charts/sn-platform-slim/templates/broker/_broker.tpl
charts/sn-platform-slim/templates/proxy/_proxy.tpl
charts/sn-platform/templates/bookkeeper/_autorecovery.tpl
charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
charts/sn-platform/templates/broker/_broker.tpl
charts/sn-platform/templates/proxy/_proxy.tpl

Fixes https://github.com/streamnative/eng-support-tickets/issues/2835

Add `"max_returned_metrics": 1000000`

---

charts/sn-platform-slim/templates/bookkeeper/_autorecovery.tpl
charts/sn-platform-slim/templates/bookkeeper/_bookkeeper.tpl
charts/sn-platform-slim/templates/broker/_broker.tpl
charts/sn-platform-slim/templates/prometheus/_prometheus.tpl
charts/sn-platform-slim/templates/proxy/_proxy.tpl
charts/sn-platform-slim/templates/zookeeper/_zookeeper.tpl
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/bookkeeper/_autorecovery.tpl
charts/sn-platform/templates/bookkeeper/_bookkeeper.tpl
charts/sn-platform/templates/broker/_broker.tpl
charts/sn-platform/templates/prometheus/_prometheus.tpl
charts/sn-platform/templates/proxy/_proxy.tpl
charts/sn-platform/templates/vault/_vault.tpl
charts/sn-platform/templates/zookeeper/_zookeeper.tpl
charts/sn-platform/values.yaml

Fixes #<xyz>
```
datadog:
component: datadog
namespace: snplatform
adVersion: v2
components:
zookeeper:
enabled: true
metrics: [
"\".*\""
]
custom_instance_configs: {}
bookkeeper:
enabled: true
metrics: [
"\".*\""
]
custom_instance_configs: {}
autorecovery:
enabled: true
metrics: [
"\".*\""
]
custom_instance_configs: {}
broker:
custom_instance_configs: 
max_returned_metrics: 1000000
kafka_consumer_custom_instance_configs: 
monitor_unlisted_consumer_groups: true
monitor_all_broker_highwatermarks: false
security_protocol: "SASL_PLAINTEXT"
sasl_mechanism: "PLAIN"
sasl_plain_username: "user"
sasl_plain_password: "token:<your-token>"
```
*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to …

Support custom config for datadog agent

---

charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Support load token from file for detector

---

charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Fixed volume mount check

---

charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml
charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Revert detector config

---

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform-slim/values.yaml
charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Support adding annotation to pvc

---

charts/sn-platform-slim/templates/broker/broker-cluster.yaml
charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml
charts/sn-platform/templates/broker/broker-cluster.yaml
charts/sn-platform/templates/proxy/proxy-cluster.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Fixed auth secret function params

---

charts/sn-platform/templates/broker/broker-cluster.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Fixed sn-platform component type

---

charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Upgrade private cloud console to 2.3.16 version

---

charts/sn-platform-slim/values.yaml
charts/sn-platform/values.yaml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Change default configuration for persistence policy to (2-2-2)
