streamnative/charts

charts/pulsar/values.yaml
Fixes: #49 
Update grafana dashboard image to 0.0.5
=> Update grafana dashboard image to 0.0.5

charts/pulsar/templates/_proxy.tpl
*Motivation*
If proxy is protected by authentication, bearer token is required.
=> Add bearer token to proxy datadog annotation

charts/pulsar/templates/bookkeeper-service.yaml
*Motivation*
bookkeeper uses statefulset for getting stable bookie identifiers. it is okay to publish endpoints that are not ready because bookkeeper client already has the ability to handle bookie failures.
=> Publish not ready addresses for bookkeeper pods

charts/pulsar/templates/proxy-service.yaml
- Fix proxy cluster IP
Maybe we don't need to assign a clusterIP:
```
sn-platform-pulsar-proxy                    ClusterIP      10.12.14.249   <none>          8080/TCP,6650/TCP            4m8s
```
=> Fix proxy cluster IP

charts/pulsar/templates/bookkeeper/_autorecovery.tpl, charts/pulsar/templates/bookkeeper/_bookkeeper.tpl, charts/pulsar/templates/broker/_broker.tpl, charts/pulsar/templates/pulsar-manager/_pulsar_manager.tpl, charts/pulsar/templates/toolset/_toolset.tpl, charts/pulsar/templates/zookeeper/_zookeeper.tpl
Fixes: #105 
Fix missed instances of the old way of setting the namespace in some of the .tpl files:
- autorecovery
- bookkeeper
- broker
- pulsar_manager
- toolset
- zookeeper
=> [Issue:105]Fallback to Helm .Release.Namespace when .namespace not defined

charts/pulsar/templates/bookkeeper/bookkeeper-autorecovery-statefulset.yaml, charts/pulsar/templates/bookkeeper/bookkeeper-statefulset.yaml, charts/pulsar/templates/broker/broker-statefulset.yaml, charts/pulsar/templates/proxy/proxy-statefulset.yaml, charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml
*Motivation*
environment variables are already taken by bash scripts. We don't need to substitute them.
=> Don't substitute environment variables

charts/pulsar/templates/control-center/_control_center.tpl
*Motivation*
Fixes #111
In 1.2.1, we refactor the chart to support providing a domain suffix. This refactor
introduces an empty domain for control_center_domain.
*Modification*
Change the code to always generate a domain name for redirect.host.
=> Fix empty redirect.host value

charts/pulsar/templates/_helpers.tpl, charts/pulsar/templates/broker/broker-configmap.yaml, charts/pulsar/templates/broker/broker-service-ingress.yaml, charts/pulsar/templates/broker/broker-statefulset.yaml, charts/pulsar/templates/detector/pulsar-detector-statefulset.yaml, charts/pulsar/templates/proxy/proxy-configmap.yaml, charts/pulsar/templates/proxy/proxy-statefulset.yaml, charts/pulsar/values.yaml
- Allow broker to advertise PodIP as the broker addresses. This would simplify vpc peering setup.
- Add `clusterName` setting. So the cluster name can be set separately.
- Add a broker ingress. The broker integress can be used for internal accesses (including geo-replication).
=> A few enhancements for geo-replication

.ci/clusters/values-bk-tls.yaml, .ci/clusters/values-broker-tls.yaml, .ci/clusters/values-function.yaml, .ci/clusters/values-jwt-asymmetric.yaml, .ci/clusters/values-jwt-symmetric.yaml, .ci/clusters/values-local-pv.yaml, .ci/clusters/values-pulsar-image.yaml, .ci/clusters/values-tls.yaml, .ci/clusters/values-zk-tls.yaml, .ci/clusters/values-zkbk-tls.yaml, .ci/helm.sh, charts/pulsar/templates/control-center/control-center-ingress.yaml, charts/pulsar/templates/proxy/_proxy.tpl, charts/pulsar/templates/proxy/proxy-configmap.yaml, charts/pulsar/templates/pulsar-cluster-initialize.yaml, charts/pulsar/templates/zookeeper/gen-zk-conf.yaml, charts/pulsar/templates/zookeeper/zookeeper-configmap.yaml, charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml, charts/pulsar/values.yaml
*Modifications*
Fixes #113 
- zookeeper: bug fixes to support adding zookeeper pods as observers to an existing zookeeper cluster
- proxy: allow proxy to be configured to use an existing broker cluster
- pulsar-manager: fix pulsar-manager secrets
=> Changes to support migrating a Pulsar cluster to another

charts/pulsar/values.yaml
- Update grafana dashboard image version to 0.0.9
=> Update grafana dashboard image version to 0.0.9

charts/pulsar/templates/bookkeeper/_bookkeeper.tpl, charts/pulsar/templates/bookkeeper/bookkeeper-statefulset.yaml, charts/pulsar/templates/prometheus/prometheus-pvc.yaml, charts/pulsar/templates/pulsar-manager/pulsar-manager-pvc.yaml, charts/pulsar/templates/zookeeper/_zookeeper.tpl, charts/pulsar/values.yaml
In reference to #126 this PR adds `storageClassName` values to all stateful components.
This lets you use previously defined storage classes for these components instead of relying on the default or creating new ones for every component.
=> add storageClassNames to values and all stateful components

charts/pulsar/Chart.yaml
*Motivation*
based on [helm documentation](https://helm.sh/docs/topics/charts/),
the `appVersion` is the version of the app that this contains. Since the repo
is using 2.6.0 image, update `appVersion` to 2.6.0
=> Update appVersion to 2.6.0 (#36)

charts/pulsar/templates/broker/function-worker-configfile-configmap.yaml, charts/pulsar/values.yaml
*Motivation*
The pulsarRootDir is configured twice in the function worker configfile. This can result in function worker using a wrong root dir.
This change remove the duplicated setting.
=> pulsarRootDir was configured twice

charts/pulsar/templates/broker/broker-statefulset.yaml
*Motivation*
In #130, we changed the helm chart to load the function worker config file from a configmap.
Hence the mounted config file is readonly. We don't need to apply the environment variables to function worker config file anymore.
=> Don't apply environment variables to function worker yaml file

.ci/clusters/values-service-account.yaml, .github/workflows/pulsar_service_account.yml, charts/pulsar/templates/bookkeeper/_bookkeeper.tpl, charts/pulsar/templates/bookkeeper/bookkeeper-cluster-role-binding.yaml, charts/pulsar/templates/bookkeeper/bookkeeper-service-account.yaml, charts/pulsar/templates/bookkeeper/bookkeeper-statefulset.yaml, charts/pulsar/templates/broker/_broker.tpl, charts/pulsar/templates/broker/broker-cluster-role-binding.yaml, charts/pulsar/templates/broker/broker-service-account.yaml, charts/pulsar/templates/broker/broker-statefulset.yaml, charts/pulsar/templates/detector/_detector.tpl, charts/pulsar/templates/detector/pulsar-detector-service-account.yaml, charts/pulsar/templates/detector/pulsar-detector-statefulset.yaml, charts/pulsar/templates/prometheus/_prometheus.tpl, charts/pulsar/templates/prometheus/prometheus-statefulset.yaml, charts/pulsar/templates/prometheus/pulsar-operators-rbac.yaml, charts/pulsar/templates/proxy/_proxy.tpl, charts/pulsar/templates/proxy/proxy-service-account.yaml, charts/pulsar/templates/proxy/proxy-statefulset.yaml, charts/pulsar/values.yaml
*Motivation*
In certain deployment, people would like to deploy Pulsar using existing service accounts.
This change is to make sure creating service accounts is optional and user can configure to use existing service accounts.
=> Make service account configurable

charts/pulsar/templates/bookkeeper/_bookkeeper.tpl, charts/pulsar/templates/bookkeeper/bookkeeper-statefulset.yaml
*Motivation*
If no storage class name is specified, the bookkeeper statefulset will be using an empty storage class name.
It will cause pvc pending in creating pv. Because no storage class name is found.
```
storageClassName: ""
```
This change fixes the issue.
=> Fix empty storageClassName issue

charts/pulsar/templates/external-dns/external-dns-rbac.yaml, charts/pulsar/templates/external-dns/external-dns.yaml, charts/pulsar/templates/proxy/_proxy.tpl, charts/pulsar/templates/proxy/proxy-configmap.yaml, charts/pulsar/templates/toolset/_toolset.tpl, charts/pulsar/templates/toolset/toolset-configmap.yaml, charts/pulsar/values.yaml, scripts/cert-manager/install-cert-manager.sh
This commit does a few main things:
1. Updates cert-manager to a more modern version
2. Updates external-dns to a more modern version
3. Fixes that if we are using lets encrypt we don't try and mount CA if
we have trusted cert
=> Upgrade cert-manager and external-dns + tweaks

charts/pulsar/templates/prometheus/_prometheus.tpl, charts/pulsar/templates/prometheus/prometheus-configmap.yaml, charts/pulsar/templates/prometheus/prometheus-statefulset.yaml, charts/pulsar/templates/proxy/websocket-configmap.yaml, charts/pulsar/values.yaml
The main change of this commit is to support having datadog scrape from
the prometheus federation endpoint. This is useful along with the small
change for adding in custom relabel configs, allow for custom handling
of labels and then getting those modified labels values into datadog.
There is also a small fix here for making the websocket work with a
trusted CA
=> Add support for datadog prom federation, minor tweaks

charts/pulsar/templates/zookeeper/gen-zk-conf.yaml
Rest of zookeeper is placed in namespace pulsar.namespace not .Values.namespace. Thanks.
=> Fix zk configmap namespace

charts/pulsar/templates/broker/broker-service-ingress.yaml, charts/pulsar/templates/broker/broker-service.yaml, charts/pulsar/templates/broker/broker-statefulset.yaml
Currently there are uppercase characters in the label which causes invalid value errors, I have converted them all to lowercase which should resolve this issue. Thanks.
=> Update kafkaPlainText label to DNS-1123 compliant label

charts/pulsar/templates/pulsar-manager/pulsar-manager-initialize.yaml
In the helm chart template for pulsar-manager initialization,
if token auth is enabled, the initial superuser creation shell
script won't work with pulsar-manager >= 0.2.0 because of a missing
CSRF_TOKEN.
Add this to the curl command so it works.
=> k8s/helm pulsar-manager fix missing CSRF_TOKEN

charts/pulsar/values.yaml
**Motivation**
We have a patch for the pulsar-metadata-tool 2.7.0 and named it `2.7.0-1`.  It will follow the 2.7.1.x release name to release after this release.
=> Update the metadata tool version

charts/pulsar/templates/tls/tls-certs-internal.yaml
---
*Motivation*
Reduce the TLS command name to avoid getting a too long name
that could not generate a certificate.
=> Reduce the TLS common name length

charts/pulsar/requirements.yaml, charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml, charts/pulsar/templates/presto/presto-worker-configmap.yaml, charts/pulsar/values.yaml
**Motivation**
Add [Superset](https://github.com/apache/superset) as a dependency to allow pulsar-sql to connect.
**Modification**
- Change pulsar-sql status check endpoint. The `/v1/cluster` already removed in trino. https://github.com/trinodb/trino/issues/3661
- `hostname -i` will return the host IP, not the hostname. `/v1/node` will return an FQDN
=> Add Superset as a dependency to allow pulsar-sql to connect

charts/pulsar/templates/prometheus/prometheus-configmap.yaml, charts/pulsar/templates/prometheus/pulsar-operators-rbac.yaml
In the event of using a prometheus that can't read a whole cluster and
only a subset of data, we need to set some different rbac and config
policies.
This was started before, but now fixes a few issues with that
=> Fix rbac/config for namespace only prom

charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml, charts/pulsar/values.yaml
---
*Motivation*
Different pulsar version is with different presto version. Presto
status check path is changed when upgrading pulsar version. Allow
configure the probe path for starting up different pulsar version.
=> Allow configure the presto probe path

charts/pulsar/templates/pulsar-cluster-initialize.yaml, charts/sn-pulsar/templates/pulsar-cluster-initialize.yaml
---
*Motivation*
The OPTS only used when enable the tls on zookeeper, if we disable
the TLS and doing restoration, the cleanup job in the pulsar init job
will failed to get the TLS related files.
=> Fix the wrong start scripts when enable restoring

charts/pulsar/templates/bookkeeper/bookkeeper-cluster-initialize.yaml, charts/pulsar/templates/pulsar-cluster-initialize.yaml, charts/pulsar/templates/zookeeper/zookeeper-restore-configmap.yaml, charts/pulsar/values.yaml
---
*Motivation*
The pulsar cluster init job will run after the bookie init.
If we restore a cluster with the same name of the old cluster,
it will fail to start bookie with mismatch cookie error.
So we allow to cleanup /ledgers path to cleanup the bookie metadata.
So we can initialize the cluster with the restore point successfully.
=> Run the cleanup in the bookie init job

charts/sn-platform/Chart.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/broker/broker-service.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform/values.yaml
Revert controller related patches as chart's broker headless service name clash with operator generated broker service's internal service name so the headless service won't be created, revert for now to unblock customer.
=> Revert controller related patches

charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml
Only reference the secret for credentials on broker and proxy when the authentication is enabled. Otherwise the broker and proxy cannot run properly without authentication.
=> Allow authentication to be disabled in pulsar

charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
Exception: 
```
Error: ZooKeeperCluster.zookeeper.streamnative.io "pulsar-sn-platform-zookeeper" is invalid: spec.persistence.dataLog.resources.requests.storage: Invalid value: "integer": spec.persistence.dataLog.resources.requests.storage in body must be of type string: "integer"
```
=> Fixed zookeeper storage size type

charts/sn-platform/templates/grafana/grafana-deployment.yaml, charts/sn-platform/templates/grafana/grafana-statefulset.yaml
Document https://grafana.com/docs/grafana/latest/administration/configuration/#root_url
This is the full URL used to access Grafana from a web browser. This is important if you use Google or GitHub OAuth authentication (for the callback URL to be correct).
=> Fixed grafana root url

charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml, charts/sn-platform/templates/presto/presto-coordinator-statefulset.yaml
Previously, this was changed to be a seperate service, however, this
seems incorrect.
The serviceName should match the name of K8S service which is used for
internal communication.
This effectively reverts #271
@zymap Can you provide some context on why this change was made in the first place?
=> Restore presto service to match service name

charts/sn-platform/values.yaml
When launching clusters, I had my console fail to come up because the vault-init job was erroring with errors like:
```
...vault-unseal-keys" not found   
```
That turned out to be because the vault statefulset wasn't able to launch containers, which was failing because of errors like:
```
Warning  FailedCreate      41s (x19 over 6m41s)  statefulset-controller  create Pod pulsar-blt-sn-platform-vault-0 in StatefulSet pulsar-blt-sn-platform-vault failed error: Pod "pulsar-blt-sn-platform-vault-0" is inv │
│ alid: [spec.volumes[0].name: Invalid value: "pulsar-blt-sn-platform-vault-": a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-n │
│ ame',  or '123-abc', regex used for validation is …
```
=> Prevent failures to launch SN console due to vault init failures

charts/sn-platform/values.yaml
Bump the `pulsar_metadata` image version from 2.8.1.0 to 2.8.1.4
=> fix(version): bump pulsar_metadata image version

charts/pulsar/templates/control-center/control-center-ingress.yaml, charts/pulsar/templates/external-dns/external-dns-rbac.yaml, charts/pulsar/templates/external-dns/external-dns.yaml, charts/pulsar/templates/tls/_tls.tpl, charts/pulsar/templates/tls/tls-cert-public-issuer.yaml, charts/pulsar/templates/tls/tls-certs-public.yaml, charts/pulsar/values.yaml
This commit adds support for using an existing install of external DNS and allowing to override the issuer for certs.
This is part of an effort to refactor to extract out some of the components to be managed outside of these charts
=> support use existing external dns and additional cert-manager options

charts/sn-platform/templates/broker/broker-statefulset.yaml, charts/sn-platform/templates/proxy/proxy-statefulset.yaml
Add secretRef of vault key to broker & proxy pods only when auth & vault are both enabled.
=> Allow sn-platform to disable auth without operator

charts/sn-console/values.yaml, charts/sn-platform/values.yaml
When starting platform, some users often forget to configure the organization and instance name, so add a default value here, and you can override it in your custom values.yaml file
=> Add default org and instance name for console

charts/pulsar/values.yaml
We don't have the 0.6.0 image tag for [streamnative/pulsar-manager](https://hub.docker.com/r/streamnative/pulsar-manager/tags), so correct the tag to 0.3.0
=> fix(charts): correct the pulsar manager image version

charts/sn-platform/templates/entities/connection.yaml
It should only setup authentication of pulsar connection when auth.authentication is enabled
=> Fix issue of pulsar connection authentication

charts/sn-platform/templates/detector/pulsar-detector-statefulset.yaml, charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
If components.vault is false, the pods of detector and console will get `CreateContainerConfigError` status, because vault related secret is not found.
=> Fix issue that the pods of detector and console is not running if vault is false

charts/sn-platform/templates/pulsar-cluster-initialize.yaml, charts/sn-platform/values.yaml
The installation gets blocked because of the image error
```shell
test-pulsar-sn-platform-bookie-0            0/1     Init:0/1                0          2m24s
test-pulsar-sn-platform-bookie-1            0/1     Init:0/1                0          2m24s
test-pulsar-sn-platform-bookie-2            0/1     Init:0/1                0          2m24s
test-pulsar-sn-platform-bookie-init-b5mdd   1/1     Running                 0          2m23s
test-pulsar-sn-platform-broker-0            0/1     Init:0/2                0          2m24s
test-pulsar-sn-platform-proxy-0             0/1     Init:0/2                0          2m24s
test-pulsar-sn-platform-pulsar-init-6jzq6   0/1     Init:InvalidImageName   0          2m23s
test-pulsar-sn-platform-recovery-0          0/1     Init:0/1                0 …
```
=> Fix the image tag of pulsar init job is empty

charts/sn-platform/values.yaml
The replicas of the bookkeeper will be updated to 3 by the operator even you set a smaller value, because the minimum number of bookies is three according to the [docs](https://bookkeeper.apache.org/archives/docs/master/bookkeeperConfig.html)
Add a comment to explain it to the user
=> Add the comment for the replicaCount of bookkeeper

charts/sn-platform/templates/detector/_detector.tpl, charts/sn-platform/templates/detector/pulsar-detector-statefulset.yaml
We want the detector to be able to use different endpoints, potentially even "hairpin" back to external endpoint.
We should make this automatic and do the best thing based on other values, for but now just starting with custom endpoints.
=> add support for custom urls to detector

charts/sn-platform/templates/vault/vault-configmap.yaml, charts/sn-platform/templates/vault/vault-initialize.yaml
Vault has a job and configmap are controlled by `.Values.initialize`, if initialize is false, the pod broker and pulsar-detector will get status `reateContainerConfigError` because the secret `xxx-vault-secret-env-injection` is not generated.
I think the vault related resources should only be controlled by `.Values.components.vault`
```shell
Events:
Type     Reason     Age               From               Message
----     ------     ----              ----               -------
Normal   Scheduled  73s               default-scheduler  Successfully assigned fswang/pulsar-sn-platform-broker-0 to gke-sn-seagull-test-default-node-pool-6e1e7002-hkb7
Normal   Pulled     73s               kubelet            Container image "streamnative/sn-platform:2.8.1.5-oauth2" already present on machine
Normal …
```
=> Fix issue that pod broker and pulsar-detector will get error if initialize is false as default

charts/pulsar-operator/Chart.yaml, charts/pulsar-operator/values.yaml
Upgrade pulsar-operator image to v0.8.21 for the new feature
- proxy external service support extra types ClusterIP, NodePort
- Istio app labeling support
=> Release pulsar-operator to 0.8.21

charts/function-mesh-operator/templates/controller-manager-deployment.yaml, charts/function-mesh-operator/templates/controller-manager-rbac.yaml
The function mesh operator doesn't work if the namespace is not `default`, because it doesn't use the release namespace in the deployment and service account. but `ClusterRoeBinding` will use the service account with namespace. This will cause the permission issue.
```shell
tem:serviceaccount:default:function-mesh-controller-manager" cannot list resource "functionmeshes" in API group "compute.functionmesh.io" at the cluster scope
E0112 04:01:48.479668       1 reflector.go:178] k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.Sink: sinks.compute.functionmesh.io is forbidden: User "system:serviceaccount:default:function-mesh-controller-manager" cannot list resource "sinks" in API group "compute.functionmesh.io" at the cluster scope
E0112 04:01:49.537523 …
```
=> Use release namespace in deployment and serviceaccount

charts/pulsar/templates/broker/broker-configmap.yaml, charts/pulsar/values.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/broker/broker-configmap.yaml, charts/sn-platform/values.yaml
In KoP doc, auth is disabled by default, so if we enable auth for KoP by default might cause
surprise for user following KoP doc.
ref: https://github.com/streamnative/kop/blob/master/docs/security.md
=> Disable authentication for KoP by default.

charts/sn-platform/templates/control-center/_control_center.tpl, charts/sn-platform/templates/control-center/control-center-ingress.yaml
Resolve https://github.com/streamnative/data-plane-epics/issues/1
When installing sn-platform by the chart, it will get these warnings
```shell
W0126 15:01:15.043974   85780 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0126 15:01:15.213499   85780 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0126 15:01:24.922246   85780 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0126 15:01:47.110670   85780 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0126 …
```
=> Upgrade deprecated Ingress apiVersion extensions/v1beta1 to networking.k8s.io/v1

charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/templates/vault/vault-initialize.yaml, charts/sn-platform/templates/vault/vault-public-key-secret.yaml, charts/sn-platform/values.yaml
Secret:
```
apiVersion: v1
data:
publicKey: ""
kind: Secret
metadata:
annotations:
meta.helm.sh/release-name: pulsar
meta.helm.sh/release-namespace: snpe
labels:
app.kubernetes.io/managed-by: Helm
name: pulsar-sn-platform-vault-public-key
namespace: snpe
type: Opaque
```
* Add an option `readPublicKeyFromFile` `publicKeyPath` and `publicKeySecret` to support reading public keys from secret file
* Add a secret for vault public key file
=> Support mount public key from secret file

charts/sn-platform/templates/control-center/_control_center.tpl, charts/sn-platform/templates/control-center/ingress-controller-deployment.yaml, charts/sn-platform/templates/control-center/ingress-controller-rbac.yaml
To support installing the chart sn-platform in k8s v1.22+, the [PR](https://github.com/streamnative/charts/pull/447) had upgraded the deprecated apiVersion `extensions/v1beta1` of `Ingress` to `networking.k8s.io/v1`. But according to the [doc](https://kubernetes.io/blog/2021/07/26/update-with-ingress-nginx/), it will also need to upgrade the version of ingress nginx to `v1.x.x` for k8s v1.22. 
This PR is going to upgrade the ingress nginx image to use [v1.1.1](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.1.1) when the k8s version is v1.22+, and keep using `0.26.2` for the older versions.
According to the doc, only v1.1.1 supports k8s v1.23, so use this version directly.
But this pr will not use the new feature  `IngressClass` for now,  keep using the annotation …
=> [sn-platform]Upgrade nginx ingress controller to v1.1.1 for k8s v1.22+

charts/sn-platform/templates/vault/_vault.tpl, charts/sn-platform/templates/vault/vault-statefulset.yaml, charts/sn-platform/values.yaml
Add annotation on vault to support integrate with datadog and allow setting additional toleration and nodeSelector info on vault pod.
=> Support datadog integration for vault.

.github/PULL_REQUEST_TEMPLATE.md
*Motivation*
Introduce a pull request template to enforce contributors to provide
sufficient context for the pull request and also provide doc-related
information
=> [workflow] Add a pull request template

.github/workflows/documentbot.yml
We want to keep the same doc label workflow as `apache/pulsar`
- Add `documentbot.yml` workflow
=> [CI]Add doc label workflow

charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml, charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml, charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml, charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml, charts/pulsar-operator/templates/pulsar-operator/rbac.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml
Allow customize Pulsar Cluster name for operator deployment.
Update operator crds, set clustername on pulsarbroker/pulsarproxy object is specified.
Doc about clustername should already be there.
=> Allow customize Pulsar Cluster name for operator deployment.

charts/pulsar/templates/control-center/_control_center.tpl, charts/pulsar/templates/control-center/control-center-ingress.yaml, charts/pulsar/values.yaml
Fixes #507 
Addressing issues with control center's the api version, annotations, and the FQDN that gets built so that this can be deployed on openshift.   
1) Added logic around the `apiversion` in the file `control-center-ingress.yaml` by using the value of `deployment.openshift` being true or false.
2) Added the same logic around the annotation `kubernetes.io/ingress.class: nginx` to address how openshift handles ingress objects and allowing for routes to be created.
3) Added logic in file `_control_center_tpl`  in section `define pulsar.control_center_domain` to build the URL FQDN that openshift expects which also builds the routes.
I made comments in the value.yaml for what this new value does. At this point it is only a few items to change …
=> [charts/pulsar] Fix issues with openshift deployments

charts/sn-platform/Chart.yaml
* Upgrade sn platform version to 1.2.36 for solve this exception:
```
Downloading loki-stack from repo https://grafana.github.io/loki/charts
Deleting outdated charts
Successfully packaged chart and saved it to: /home/runner/work/charts/charts/.chart-packages/sn-platform-1.2.35.tgz
Uploading charts...
Error: error creating GitHub release: POST https://api.github.com/repos/streamnative/charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```
=> Update sn platform version to 1.2.36

charts/local-storage-provisioner/Chart.yaml
Fixes #502
Update local-storage-provisioner chart version to use app/v1 for DaemonSet.
Update chart version.
=> Update local-storage-provisioner chart version to 1.1.0

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-statefulset.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/broker/broker-statefulset.yaml, charts/sn-platform/templates/detector/pulsar-detector-statefulset.yaml, charts/sn-platform/templates/extra.yaml, charts/sn-platform/templates/presto/presto-coordinator-configmap.yaml, charts/sn-platform/templates/presto/presto-worker-configmap.yaml, charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/templates/proxy/proxy-statefulset.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform/templates/zookeeper/zookeeper-statefulset.yaml, charts/sn-platform/values.yaml
This commit contains fixes for a few different problems, but primarily is to support additional flexibility needed to customize some aspects of having the operators adopt the ZK and BK resources. 
This commit also adds some additional options that were present in previous versions, but were to be supported when deploying with the operators, such as adding support for custom anti-affinity in most components.
A few other small features are added:
- support for advanced zookeeper options, present in operators
- additional arguments to the detector
- support for arbitrary extra resources
See above
All of the features here are advanced usages of the charts, with adoption being something requires …
=> Merge support for adoption of some ZK and BK resources

charts/pulsar/templates/toolset/toolset-statefulset.yaml, charts/pulsar/values.yaml, charts/sn-platform/templates/toolset/toolset-statefulset.yaml, charts/sn-platform/values.yaml
Add support for extra env vars for toolset pods
Adds `extraEnv` to the toolset pods in pulsar and sn-platform charts
*(or)*
*(or)*
*(example:)*
=> Toolset extra env

charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml, charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml, charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml, charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform/values.yaml
Able to configure SN Platform to use a private registry.
- New feature values `global.imagePullSecret` in `charts/sn-platform`
- New CRDs that support imagePullSecrets in `charts/pulsar-operator`
*(or)*
*(or)*
*(example:)*
Just like the …
=> Support ImagePullSecrets in pulsar components

charts/pulsar-operator/Chart.yaml, charts/pulsar-operator/values.yaml
Upgrade operators' image tags. 
- Upgrade operators' image tags to v0.9.4
- Switch to use cloudsmith as the image registry.
=> [pulsar-operator] upgrade operators

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
Fixes #550 
Adjust the syntax position of imagePullSecrets in helm templates.
The position of `imagePullSecrets` if-statement.
Thanks @MarvinCai for discovering this error.
=> Adjust the syntax position of imagePullSecrets in helm templates

charts/sn-platform/templates/tls/tls-certs-internal.yaml, charts/sn-platform/values.yaml
Fixes https://github.com/streamnative/charts/issues/554
Fix the manifests for Certificate V1 based on the [API document](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate).
- Move `organization` to `subject.organizations`
- Move `keySize`, `keyAlgorithm`, `keyEncoding` to under `privateKey.size`, `privateKey.algorithm`, and `encoding`
- Fix the default key encoding and algorithm name for V1
- Fix the certificate name for streamnative console
=> [charts/sn-platform] Fix certificate templates

.ci/chart_test.sh, .ci/clusters/values-upgrade.yaml, charts/pulsar/templates/broker/broker-configmap.yaml, charts/pulsar/values.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/broker/broker-configmap.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
* Remove offload use flag
* * Remove offload use flag
*(or)*
*(or)*
*(example:)* …
=> Fixed remove offload use flag

charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/values.yaml
Allow customizing port exposed by Proxy ingress service.
Add value as portOverride and apply if configured.
=> Allow customizing port exposed by Proxy ingress service.

charts/sn-platform/templates/bookkeeper/bookkeeper-autorecovery-statefulset.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-statefulset.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/broker/broker-statefulset.yaml, charts/sn-platform/templates/control-center/ingress-controller-deployment.yaml, charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml, charts/sn-platform/templates/node-exporter/node-exporter.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/templates/proxy/proxy-statefulset.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform/templates/zookeeper/zookeeper-statefulset.yaml, charts/sn-platform/values.yaml
Fixes #545
If user don't want prometheus to scrape metrics from some components or already integrated with 3rd party metrics system then chart should provide option to turn off the prometheus scraping.
Add option to turn off prometheus scarping annotation.
=> Add option to turn off prometheus scarping annotation.

charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/values.yaml
Fix ExternalServiceTemplate for Proxy.
Add port name when overriding http port.
=> Add port name in ExternalServiceTemplate for http port override.

charts/sn-platform/templates/vault/vault-statefulset.yaml
Fixes #571 
Fix the manifest issue that makes some fields out of the `components.vault` control which will interrupt the chart installation when setting `components.vault` to `false`
Fix the position of related`{{- end }}`
=> Fix the manifest issue that makes some fields out of the `components.vault` control

charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/values.yaml
This allows customers to mount extra secrets or specify extra environment variables.
A common use case is to mount the oauth2 private key for oauth2 authentication.
- introduce `extraSecretRefs` for broker and proxy
- introduce `extraEnv` for broker and proxy
*(or)*
*(or)*
*(example:)* …
=> [sn-platform] support extra secretRefs and variables for proxy and broker

charts/sn-platform/templates/tls/tls-certs-internal.yaml, charts/sn-platform/templates/tls/tls-certs-public.yaml
Fixes #569
Due to a [cert-manager issue](https://github.com/cert-manager/cert-manager/issues/4573),
cert-manager is not able to generate certificate if JKS keystore creation is enabled.
This pull request disables JKS keystore creation if kop is not enabled.
This is a bug fix. 
=> Disable JKS keystore creation if kop is not enabled

charts/sn-platform/templates/broker/broker-cluster.yaml
```
client.go:128: [debug] creating 41 resource(s)
Error: INSTALLATION FAILED: PulsarBroker.pulsar.streamnative.io "pulsar23-sn-platform" is invalid: spec.pod.vars: Invalid value: "null": spec.pod.vars in body must be of type array: "null"
helm.go:84: [debug] PulsarBroker.pulsar.streamnative.io "pulsar23-sn-platform" is invalid: spec.pod.vars: Invalid value: "null": spec.pod.vars in body must be of type array: "null"
```
* Update broker cluster yaml file
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end …
=> Fixed broker cluster vars

charts/pulsar/values.yaml
Right now, when enabling pulsar detector, the pod crashloops because bin/pulsar-detector can't be found in the sn-pulsar image. This fixes that by referencing the correct image.
Fixes #529
Enabling pulsar detector did not work as intended, after investigation this was the solution: correcting the image.
Change the pulsar detector source image `sn-platform` instead of `sn-pulsar`
=> [charts/sn-pulsar] Change the pulsar detector image to sn-platform

charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml
Fixed exception: 
```
client.go:98: [debug] creating 35 resource(s)
Error: PulsarBroker.pulsar.streamnative.io "pulsar-poc-sn-platform" is invalid: spec.pod.secretRefs: Invalid value: "null": spec.pod.secretRefs in body must be of type array: "null"
helm.go:75: [debug] PulsarBroker.pulsar.streamnative.io "pulsar-poc-sn-platform" is invalid: spec.pod.secretRefs: Invalid value: "null": spec.pod.secretRefs in body must be of type array: "null"
```
*(or)*
*(or)*
*(example:)*
- *Added …
=> Fixed secretRefs check

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
* Some users complained that some custom configurations could not be loaded into the bookkeeper configuration  so this pr fixes it
* Support load custom configData for bookkeeper
*(or)*
*(or)*
*(example:)*
Need to update …
=> Support custom config data for bookkeeper

charts/sn-platform/templates/vault/vault-statefulset.yaml
Fixed upgrade execption:
```
vaultContainerSpec:
name: pulsar25-sn-platform-vault-vault-container-spec
readinessProbe:
failureThreshold: 2
httpGet:
path: /v1/sys/init
port: api-port
scheme: HTTP
```
vault-operator 1.15.1
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Vault.spec.vaultContainerSpec): missing required field "name" in com.banzaicloud.vault.v1alpha1.Vault.spec.vaultContainerSpec
helm.go:84: [debug] error validating "": error validating data: ValidationError(Vault.spec.vaultContainerSpec): missing required field "name" in com.banzaicloud.vault.v1alpha1.Vault.spec.vaultContainerSpec
```
=> Fixed vault container spec missing name field

charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
* Support config node selector for zookeeper
* * Support config node selector for zookeeper
*(or)*
*(or)*
*(example:)*
=> Support config node selector for zk

charts/pulsar/templates/_helpers.tpl, charts/pulsar/templates/bookkeeper/_autorecovery.tpl, charts/pulsar/templates/bookkeeper/_bookkeeper.tpl, charts/pulsar/templates/broker/_broker.tpl, charts/pulsar/templates/function-worker/_function_worker.tpl, charts/pulsar/templates/presto/_presto.tpl, charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml, charts/pulsar/templates/presto/presto-worker-statefulset.yaml, charts/pulsar/templates/proxy/_proxy.tpl, charts/pulsar/templates/pulsar-manager/_pulsar_manager.tpl, charts/pulsar/templates/toolset/_toolset.tpl, charts/pulsar/templates/zookeeper/_zookeeper.tpl, charts/pulsar/values.yaml
Fixes #563
User might have their own CA and issue cert by themself, we should support using user provided cert for components.
Add certSecretName for components which need to mount certs, so user can mount custom cert through secret.
Assuming there'll be only one CA and all cert secrets will be created in advance which will be out of scope of this chart.
=> [Pulsar] Support using custom cert via mounting custom cert secret.

charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform/values.yaml
Fixes #642 
It's feature of BookKeeperCluster and ZooKeeperCluster, We should expose the reclaim policy option (DELETE or RETAIN) to values.yaml.
- expose `spec.storage.reclaimPolicy` of BookKeeperCluster to `bookkeeper.volumes.reclaimPolicy` in values, default value is still "Delete"
- expose `spec.storage.reclaimPolicy` of ZooKeeperCluster to `zookeeper.volumes.reclaimPolicy` in values, default value is still "Delete"
=> [SN-Platform] make reclaimPolicy of zk/bk configurable

charts/sn-platform/templates/detector/pulsar-detector-statefulset.yaml
Fixes #638
Don't use hardcoded zk url for detector zk initContainer.
Use template pulsar.zookeeper.connect for detector zk initContainer.
Verified by installing the chart.
=> Use template pulsar.zookeeper.connect for detector zk initContainer.

charts/sn-platform/values.yaml
Fixes #<xyz>
Set the readinessProbe for bankVaults container as null by default to fix the issue when Istio enabld and hang the vault pod up. 
Set the readinessProbe for bankVaults container as null by default to fix the issue when Istio enabld and hang the vault pod up. 
*(or)*
*(or)* …
=> fix(sn-platform): set readinessProbe in bankVaults default as null

charts/pulsar/templates/prometheus/prometheus-configmap.yaml, charts/pulsar/values.yaml, charts/sn-platform/templates/prometheus/prometheus-configmap.yaml, charts/sn-platform/values.yaml
In some situations, we may want to add a custom scrape config, this adds
support for that in the prometheus components of both charts
Adds the ability to add extra scape rules in prom
*(or)*
*(or)*
*(example:)*
Small change with a simple new option in the values. We currently don't document …
=> Add support for additional scrape rules in prom

charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml
I've been working with Helm for around five years now. I've seen lots of mistakes, made lots of mistakes, seen a lot of fixes for templates, and made a number myself.
I've discovered in this that the easiest way to avoid template bugs is to have simpler templates. This is particularly because Helm isn't expressive and YAML cares deeply for whitespace.
[Yesterday I saw a PR](https://github.com/streamnative/charts/pull/594). The PR was great. The bug it was fixing was sadly a bug I see somewhat often. An `if` condition in the wrong place. I see this happen often in long Helm templates, especially with nested blocks. A way to avoid this pitfall is to not have as many nests.
John Tip \#1 for Helm Templating: 
Prefer this:
```
field: {{ default "foo" .Values.bar }}
```
over this:
```
{{ if …
```
=> [charts/sn-platform] Example Simplify Of Charts

charts/sn-platform/templates/vault/vault-public-key-secret.yaml
The vault secret is only needed when vault is enabled.
So checking the condition when creating the secret.
=> Check for condition when creating vault secret.

charts/sn-console/templates/console/streamnative-console-pvc.yaml
The pre-generated pvc's name doesn't match the one mounted by sts, fixing it.
Fix the generated pvc name.
=> Fix sn-console generated pvc name.

charts/sn-platform/templates/bookkeeper/bookkeeper-authorizationpolicy.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/prometheus/prometheus-configmap.yaml, charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml, charts/sn-platform/templates/zookeeper/zookeeper-authorizationpolicy.yaml
Fixes #677 
When Istio enabled, Pod to Pod(IP) communication will fail because of lack of `Host`/`SNI`.
Following the [Istio docs](https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings), we config Prometheus to scrape Pod metrics with Istio certs and let Istio Sidecar ignore the traffic.
*Only affect Istio enabled mode*
- Configure Prometheus Pod sidecar share Istio certs
- Modify Prometheus job definition to ignore non-Pulsar Pods and scrape metrics with Istio certs
- Add/Modify AuthorizationPolicy for Prometheus access BooKeeper AutoRecovery/ZooKeeper
=> [sn-platform]Fix Prometheus Scraping promblem with Istio enabled

charts/sn-platform/templates/_helpers.tpl
Fixes #<xyz>
If neither `.configData.PULSAR_GC` nor `.jvm.gcOptions` is configured, `gcOptions` may be empty, resulting in the following exception:
```
atomic being set: [bookkeepercluster.bookkeeper.streamnative.io](http://bookkeepercluster.bookkeeper.streamnative.io/) "sn-platform-bookie" is invalid: spec.autorecovery.pod.jvmOptions.gcOptions invalid value in body must be of type array null
```
* Add `gcOptions` to the if condition
*(or)*
This change is already covered by …
=> Fixed gcOptions check for jvmOptions

charts/sn-platform/templates/streamnative-console/_streamnative-console.tpl, charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml, charts/sn-platform/templates/streamnative-console/streamnative-console-service-account.yaml, charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml, charts/sn-platform/values.yaml
Fixes https://github.com/streamnative/charts/issues/687
Add a dedicated service account for the console.
Add a dedicated service account for the console.
*(or)*
*(or)*
*(example:)*
=> Add a dedicated service account for the console

charts/pulsar-operator/crds/bookkeeper.streamnative.io_bookkeeperclusters.yaml, charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarbrokers.yaml, charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml, charts/pulsar-operator/crds/zookeeper.streamnative.io_zookeeperclusters.yaml
Add description to crd so user can see detailed explanation of fields when doing kubectl explain like `kubectl explain pulsarbroker.spec.image`.
=> [Feat]Add description to crd.

charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/values.yaml
Related to https://github.com/streamnative/pulsar-operators/issues/591
Mounting additional PVC to Pulsar Broker if needed to support use case like offloading to FS where persistent storage is required.
Add PVC spec to PulsarBroker's APIObject's STS template if defined.
=> [Feat] Support adding additional PVC to Pulsar Broker.

charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml, charts/sn-platform/values.yaml
Master Issue: #716 
https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
```
--storage.tsdb.wal-compression: Enables compression of the write-ahead log (WAL). Depending on your data, you can expect the WAL size to be halved with little extra cpu load. This flag was introduced in 2.11.0 and enabled by default in 2.20.0. Note that once enabled, downgrading Prometheus to a version below 2.11.0 will require deleting the WAL.
```
* Add option for enable wal compression for prometheus
*(or)*
*(or)*
*(example:)*
- …
=> Default enable wal compression, for avoid prometheus oom

charts/sn-platform-common/templates/_commmon.tpl, charts/sn-platform-vault/templates/_vault.tpl, charts/sn-platform-vault/templates/vault-authorizationpolicy.yaml, charts/sn-platform-vault/templates/vault-clear-resource.yaml, charts/sn-platform-vault/templates/vault-configmap.yaml, charts/sn-platform-vault/templates/vault-initialize-public-key.yaml, charts/sn-platform-vault/templates/vault-initialize.yaml, charts/sn-platform-vault/templates/vault-public-key-secret.yaml, charts/sn-platform-vault/templates/vault.yaml, charts/sn-platform-vault/values.yaml
Simplify vault component name. Currently component name can look like `my-release-sn-platform-vault-vault-init`
where the component name `vault` is kind of duplicated and confusing.
Only add component name `vault` when it's needed.
=> Simplify vault component name.

charts/pulsar/templates/zookeeper/zookeeper-statefulset.yaml, charts/pulsar/values.yaml
Signed-off-by: laminar <tpiperatgod@gmail.com>
Fixes #745 
Add the probe timeout configuration to the zookeeper statefulsets in the streamnative/pulsar chart so that we can avoid probes not being ready.
add configuration for the following fields:
- zookeeper.probe.liveness.timeoutSeconds
- zookeeper.probe.readiness.timeoutSeconds
*(or)*
*(or)*
This change added tests and can be verified as …
=> feat: add probe timeout configuration for zookeeper statefulsets in streamnative/pulsar chart

charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
`.Values.configmapReload.prometheus.image.repository` configs should be replaced by `.Values.images.configmapReload.repository`. AlertManager has the correct configs while Prometheus has the legacy configs.
Replace `image: "{{ .Values.configmapReload.prometheus.image.repository }}:{{ .Values.configmapReload.prometheus.image.tag }}"` by `image: "{{ .Values.images.configmapReload.repository }}:{{ .Values.images.configmapReload.tag }}"` and remove the legacy configs in values.
This change …
=> fix(sn-platform): remove legacy image configs for configmapReload

charts/sn-platform/templates/presto/presto-coordinator-configmap.yaml, charts/sn-platform/templates/presto/presto-worker-configmap.yaml, charts/sn-platform/values.yaml
Fixes #708
Users would like to be able to include custom values in Presto `config.properties`
Added two parameters as shown below table:
| Parameter  | Type  | Default  | 
|:-:|:-:|:-:|
| `presto.coordinator.config.custom`  |  map | {}  |
| `presto.worker.config.custom`  | map  |  {} |
Example values file:
```
presto:
coordinator:
config:
custom:
sql.forced-session-time-zone: America/New_York
worker:
config:
custom:
sql.forced-session-time-zone: America/New_York   
```
*(or)*
*(or)*
*(example:)*
- *Added integration tests for …
=> Support custom configs for Presto coordinator and worker

charts/pulsar/templates/proxy/proxy-service-ingress.yaml, charts/pulsar/values.yaml
Allow customizing Proxy ingress svc https port so it's not tie to https container port. Mainly for Pulsar 2.10+ compatibility, as non-root user can't use port < 1000.
Add config to config port for Proxy https port so we can choose different port for Proxy container https port.
=> [Feat][Pulsar] Allow customizing Proxy ingress svc https port.

charts/sn-platform/templates/openshift/_openshift.tpl, charts/sn-platform/templates/openshift/scc-role.yaml, charts/sn-platform/templates/openshift/scc-rolebinding.yaml, charts/sn-platform/templates/openshift/scc.yaml, charts/sn-platform/values.yaml
Fixes #765 
We are currently only creating a new SCC by default, but we should also allow referencing an existing SCC.
Added `openshift.scc.name` for referencing the existing SCC.
*(or)*
*(or)*
*(example:)*
=> Support openshift reuse an existing SCC

charts/pulsar/templates/proxy/proxy-service.yaml, charts/pulsar/values.yaml
Follow up for https://github.com/streamnative/charts/pull/771
Also upgading Proxy service to able to customize https port mapping.
Add config for Proxy service https port, set targetPort if service port doesn't match container port.
*(or)*
*(or)*
*(example:)*
(If this PR …
=> Update Proxy service port mapping.

charts/pulsar-operator/README.md
Adding note about missing preserveUnknownFields: false from generated CRD.
=> Update readme for pulsar-operator chart.

charts/pulsar/templates/toolset/_toolset.tpl
Fix `toolset.web.service.url` template rendering when `.Values.proxy.ports.httpsServicePort` configured
=> [pulsar] Support proxy service port mapping in toolset

charts/pulsar/values.yaml, charts/sn-platform/values.yaml
Needed for https://github.com/streamnative/cloud-support-tickets/issues/104
In other sections of code, we're using/relying on Grafana 8.x. This was using 7.x which has a few bugs we are experiencing.
New base image based of grafana 8.4.3
We actually thought we were using 8.x afaik. This brings it in line.
=> Use latest grafana image (based on 8.4.3 Grafana)

charts/sn-platform/templates/broker/function-worker-configfile-configmap.yaml, charts/sn-platform/templates/function-worker/_function_worker.tpl, charts/sn-platform/templates/function-worker/function-worker-authorizationpolicy.yaml, charts/sn-platform/templates/function-worker/function-worker-statefulset.yaml, charts/sn-platform/values.yaml
- support Istio mode
- function worker compatible with TLS authentication
- add AuthorizationPolicy for function worker
- skip wait-proxy-ready initContainer when the proxy is disabled
- improve/fix function-worker TLS related configurations
=> [sn-platform] Improve function-worker compatibility

charts/pulsar/templates/zookeeper/zookeeper-configmap.yaml
Add skipACL if enabled dynamic reconfig for zookeeper.
We need to either skipACL or set a password, so use skipACL here.
*(or)*
*(or)*
*(example:)*
=> Update ZooKeeper dynamic reconfig.

charts/pulsar/templates/tls/tls-cert-public-issuer.yaml, charts/pulsar/values.yaml, charts/sn-platform/templates/tls/istio/tls-cert-public-issuer.yaml, charts/sn-platform/templates/tls/tls-cert-public-issuer.yaml, charts/sn-platform/values.yaml
Working with Pulsar in a mixed environment running on Google Kubernetes with Cloudflare for security reasons and for managing your DNS, provisioning of public TLS certificates does not work since Cloudflare is currently not supported as a DNS resolver, rendering Let's encrypt issuer nonoperative. 
three issuer templates were modified to enable Cloudflare:
- charts/sn-platform/templates/tls/istio/tls-cert-public-issuer.yaml
- charts/sn-platform/templates/tls/tls-cert-public-issuer.yaml
- charts/pulsar/templates/tls/tls-cert-public-issuer.yaml
The change was verified using single and wildcard hosts for new installations and for helm upgrade process. No other specific tests were made. 
(Your PR needs to update docs and you will update later)
Did not find any reference inside of existing …
=> Adding support for cloudflare in public certificate issuing process

charts/sn-platform/templates/broker/broker-cluster.yaml
Fixes #831 
Set resources limits/requests for `broker-metadata-init` Job.
- Remove the `.Values.zookeeper.customTools.restore.enable` condition for broker init job.
- Use `spec.initJobPod.resources` rather than `spec.initJobPod.initContainers[*].resources`. Because the Operator itself uses the latter one.
*(or)*
*(or)*
*(example:)*
(If you need …
=> [sn-platform] Fix resources limits for broker metadata init job

charts/sn-platform/templates/broker/broker-cluster.yaml
Use `.Values.zookeeper.customTools.restore.enable` control enabling cleanup initContainer in Broker initJob Pod.
**PS: Please test with a pure installation**
=> [sn-platform] Fix broker initJob definition

charts/pulsar-operator/templates/bookkeeper-operator/operator.yaml, charts/pulsar-operator/templates/pulsar-operator/operator.yaml, charts/pulsar-operator/templates/zookeeper-operator/operator.yaml
I referred the [vault-operator configs](https://github.com/banzaicloud/bank-vaults/blob/main/charts/vault-operator/README.md#configuration) and added some extra configs like `podSecurityContext`, `containerSecurityContext`, `podAnnotations` and `podLabels`
Added some extra configs like `podSecurityContext`, `containerSecurityContext`, `podAnnotations` and `podLabels`
*(or)*
*(or)*
*(example:)*
- …
=> feat(operator): Add some extra configs on operator deployment

charts/pulsar/templates/broker/_broker.tpl, charts/pulsar/templates/broker/broker-configmap.yaml, charts/pulsar/templates/broker/broker-statefulset.yaml, charts/pulsar/templates/oauth2/oauth2-secret.yaml, charts/pulsar/templates/proxy/_proxy.tpl, charts/pulsar/templates/proxy/proxy-configmap.yaml, charts/pulsar/templates/proxy/proxy-statefulset.yaml, examples/pulsar/values-oauth2.yaml
Fixes #850
Make it easy to test Pulsar with oauth2 enabled
Add the oauth2 authentication provider support to the Pulsar charts
There is an example values file, but a doc would be better
=> [Pulsar] Add oauth2 support for pulsar charts

charts/pulsar/templates/proxy/proxy-configmap.yaml
set forwardAuthorizationCredentials to true with authentication is enabled
Fixes #854
Fix proxy authentication error
Make `forwardAuthorizationCredentials` to true when authentication is enabled
bug fix
=> [charts/pulsar] fix proxy authentication error:

charts/pulsar-operator/Chart.yaml, charts/pulsar-operator/crds/pulsar.streamnative.io_pulsarproxies.yaml, charts/pulsar-operator/values.yaml
1. Upgrade pulsar-operator
1. Update PulsarProxy CRD
2. Update operators image tag to v0.12.3
=> [pulsar-operator] Upgrade to v0.12.3

.github/workflows/pulsar_upgrade.yml
Fixes #882 
apache pulsar helm chart adds a dependency, making helm install failed
Fix apache/pulsar-helm-chart to pulsar-2.9.4
=> Fix chart-testing(upgrade) job

charts/sn-platform/templates/presto/_presto.tpl, charts/sn-platform/templates/presto/presto-authrozationpolicy.yaml, charts/sn-platform/templates/presto/presto-coordinator-configmap.yaml, charts/sn-platform/templates/presto/presto-coordinator-statefulset.yaml, charts/sn-platform/templates/presto/presto-serviceentry.yaml, charts/sn-platform/templates/presto/presto-worker-configmap.yaml, charts/sn-platform/templates/presto/presto-worker-statefulset.yaml, charts/sn-platform/values.yaml
Fixes #868 
Presto coordinator and worker support tls authentication
1. Fix tls configuration of presto
```yaml
tls:
presto:
enabled: true
trustCertsEnabled: true
```
3. Add tls authentication configuration for presto
```yaml
presto:
security:
tls:
enabled: true
```
=> [sn-platform] Presto support tls authentication

charts/sn-platform/templates/presto/presto-coordinator-configmap.yaml, charts/sn-platform/templates/presto/presto-coordinator-deployment.yaml, charts/sn-platform/templates/presto/presto-worker-configmap.yaml, charts/sn-platform/templates/presto/presto-worker-deployment.yaml
Fixes #900 
- can't disable presto exporter
- Use `.Values.presto.exporter.enabled` replace `.Values.presto.exporter` as enable condition
=> [sn-platform] Fix Presto JMX exporter enable condition

.github/CODEOWNERS
Seems like the platform team is not the owner of those charts
=> Update CODEOWNERS: Remove platform team

charts/sn-console/values.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
They have provided a full analysis of the problem and a workaround for the issue:
> During K8S deployment, streamnative-console-init pod gets stuck into “NotReady” State, where injected istio-proxy container keeps “Running”.
```
pulsar-sn-platform-streamnative-console-init-dthg4    1/2     NotReady    0               3m10s
```
> Using istioctl 1.15.3 + SN:1.6.0
> Looking at the logs of the stuck NotReady pod “pulsar-sn-platform-streamnative-console-init-hxt2r”:
```
$ kubectl logs pulsar-sn-platform-streamnative-console-init-dthg4 -n pulsar
.
.
StreamNative Console is ready to use~ …
```
=> Update console version for fixed curl missing issue

charts/sn-platform/templates/_helpers.tpl, charts/sn-platform/values.yaml
Make annotation merge-metrics configurable
Define `.Values.istio.mergeMetrics`, and default value is `false`
=> [sn-platform] Make annotation merge-metrics configurable

charts/pulsar-operator/templates/bookkeeper-operator/rbac.yaml, charts/pulsar-operator/templates/zookeeper-operator/rbac.yaml
Fixes #943 
zk/bk operator don't have permission to watch Istio resources in Istio env.
Add Istio resources rbac for zk/bk operator
=> [pulsar-operator] Add Istio resource rbac for zk/bk operator

scripts/pulsar/common_auth.sh
upgrade pulsarctl default download version to support arm64(Apple M1)
=> upgrade pulsarctl default download version to support arm64(Apple M1)

charts/sn-platform/templates/tls/istio/tls-certs.yaml
* when using istio, internal issuer, the cert will failed due to issuer not found. 
* change the issuer reference name in istio cert when using internal issuer. 
- [ *] `no-need-doc` 
=> fix internal issuer reference name.

charts/sn-platform/templates/toolset/toolset-statefulset.yaml, charts/sn-platform/values.yaml
Run toolset in rootless env
- Make busybox rootless
- Add option installBusybox
=> Support rootless busybox in toolset

charts/sn-platform/templates/alert-manager/alertmanager-deployment.yaml, charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml, charts/sn-platform/values.yaml
- Define securityContext for sla detector
- Fix securityContext for alert manager
*(or)*
*(or)*
*(example:)*
=> Define securityContext for components

charts/sn-platform-slim/templates/alert-manager/alertmanager-deployment.yaml, charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml, charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml, charts/sn-platform-slim/templates/toolset/toolset-statefulset.yaml, charts/sn-platform-slim/values.yaml
=> [sn-platform-slim] Sync securityContext changes

charts/sn-platform-slim/templates/_helpers.tpl, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/_helpers.tpl, charts/sn-platform/values.yaml
Fixes #<xyz>
Pulsar Operators have the capability to auto-generate the JVM memory options based on the Pod memory size. 
By default to use the operator auto-generated JVM memory options config but also supports to override.  
*(or)*
*(or)*
*(example:)*
- …
=> [sn-platform][sn-platform-slim]: update to use the operator auto generated jvm memory options. 

charts/sn-console/Chart.yaml, charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform-slim/templates/broker/broker-cluster.yaml, charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml, charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform/values.yaml, examples/pulsar-operators/logConfig.yaml, examples/sn-platform/logConfig.yaml
Fixes #<xyz>
Add the `logConfig` CR configuration support on chart to support dynamic log config changing. 
*(or)*
*(or)*
*(example:)*
Check the box …
=> [sn-platform][sn-platform-slim]feat: add logConfig support on sn-platform & sn-platform slim charts

charts/sn-platform-slim/templates/broker/broker-secret.yaml, charts/sn-platform/templates/broker/broker-secret.yaml
The content that decodes from the secret is not correct, because it has backslashes.
```shell
"{\"client_id\":\"b097d864-4b4d-0020-a34e-0929dkjslkj29\",\"client_secret\":\"XFXXXXXXX_51ZijnihaoVqGJbbzk\"}"
```
The correct format should be like this
```shell
{"client_id":"b097d864-4b4d-0020-a34e-0929dkjslkj29","client_secret":"XFXXXXXXX_51ZijnihaoVqGJbbzk"}
```
Use the `fromYaml` first before the `toJson`.
*(or)*
*(or)*
*(example:)*
- *Extended …
=> fix: generate secret from json string

charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: missing template for proxy wss

charts/pulsar/templates/bookkeeper/bookkeeper-cluster-initialize.yaml
---
When enable tls for the zookeeper, it will write the TLS properties with PULSAR_EXTRA_OPTS as the key into the pulsar-env.sh file. The metadata tool also needs the PULSAR_EXTRA_OPTS to get the zookeeper TLS configurations. So import the PULSAR_EXTRA_OPTS into the OPTS to load the zookeeper TLS configuration.
=> Load the pulsar env as the program start options

charts/sn-platform-slim/templates/broker/broker-cluster.yaml, charts/sn-platform-slim/templates/istio/default-peerauthentication.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/istio/default-peerauthentication.yaml, charts/sn-platform/values.yaml
Fixes #1110 
Support migrate workloads from non-Istio to Istio
- Make mtls mode permissive for Istio migration
=> Support Istio migration mode

charts/sn-platform-slim/templates/toolset/jwt-secret-init-job.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/toolset/jwt-secret-init-job.yaml, charts/sn-platform/values.yaml
Fixes #1119 
- copy kubectl binary from initContainer
- Make isito-proxy quit after job completed
=> [sn-platform] Avoid downloading in jwt secret int job

charts/pulsar/templates/presto/presto-coordinator-configmap.yaml, charts/pulsar/templates/presto/presto-coordinator-statefulset.yaml, charts/pulsar/templates/presto/presto-worker-statefulset.yaml, charts/sn-platform/templates/presto/presto-coordinator-configmap.yaml, charts/sn-platform/templates/presto/presto-coordinator-deployment.yaml, charts/sn-platform/templates/presto/presto-worker-configmap.yaml, charts/sn-platform/templates/presto/presto-worker-deployment.yaml
In the pulsar image, presto is named trino. We need to adapt the related charts conf.
- Correct all the `trino` conf path.
- Use root user to run the pod in order to add configuration to `node.properties `
- Remove `node.internal-address` 
- Health check: add header when request trino API and replace internal addr with pod ip
*(or)*
*(or)*
*(example:)*
Need to update …
=> Replace presto with trino

.github/CODEOWNERS, charts/sn-platform-slim/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: wrong template for broker extraEnv

charts/pulsar-operator/Chart.yaml, charts/pulsar-operator/templates/pulsar-operator/_helpers.tpl, charts/pulsar-operator/templates/zookeeper-operator/_helpers.tpl, charts/pulsar-operator/values.yaml
Fixes #<xyz>
Upgrade the chart to use v0.17.10 operator release. 
*(or)*
*(or)*
*(example:)*
(If you need …
=> chore: upgrade pulsar operator to v0.17.10

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform-slim/templates/broker/broker-cluster.yaml, charts/sn-platform-slim/templates/zookeeper/zookeeper-backup-statefulset.yaml, charts/sn-platform-slim/templates/zookeeper/zookeeper-restore-configmap.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/zookeeper/zookeeper-backup-statefulset.yaml, charts/sn-platform/templates/zookeeper/zookeeper-restore-configmap.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: add cleanup in the bk cluster

ct.yaml
CI fails:
```
Error: Error linting charts: Could not read 'Chart.yaml': open charts/pulsar-operator/Chart.yaml: no such file or directory
```
- remove charts/pulsar-operator from ct.yaml
=> Fix CI after removal of pulsar-operator

charts/sn-platform-slim/templates/_helpers.tpl, charts/sn-platform/templates/_helpers.tpl
There will be a duplicate brokerClientAuthenticationPlugin definition when oauth and jwt are enabled simultaneously.
Rearrange the conditions so that in `pulsar.authConfiguration` template, the jwt handling is in the else branch of the oauth enabled condition.
*(or)*
*(or)*
*(example:)* …
=> fix: duplicate brokerClientAuthenticationPlugin definition when oauth and jwt are enabled simultaneously

charts/sn-platform/conf/vault/init_vault_streamnative_console/proxy-super-service-account-template.json, charts/sn-platform/conf/vault/init_vault_streamnative_console/startup.sh, charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml, charts/sn-platform/templates/vault/vault-initialize.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Support custom proxy-admin role

charts/sn-platform-slim/templates/detector/pulsar-detector-deployment.yaml, charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: detector extraArgs missed default auth configs

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform-slim/templates/broker/broker-cluster.yaml, charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml, charts/sn-platform-slim/templates/pulsar-coordinator/pulsar-coordinator.yaml, charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/templates/pulsar-coordinator/pulsar-coordinator.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> feat: add the pulsar_coordinator in the values

charts/sn-platform-slim/conf/toolset/pulsar/generate_token.sh, charts/sn-platform-slim/conf/toolset/pulsar/get_token.sh, charts/sn-platform/conf/toolset/pulsar/generate_token.sh, charts/sn-platform/conf/toolset/pulsar/get_token.sh
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: update the autoJwt script base64 commands

charts/sn-platform-slim/templates/zookeeper/zookeeper-backup-statefulset.yaml, charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform/templates/zookeeper/zookeeper-backup-statefulset.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Mount the backup/restore configmap as the env

charts/sn-platform-slim/values.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> chore: upgrade pulsar image to 3.2

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
I think this is a legacy issue to use hard code log4j2 config.
Now we are using `logConfig` in CR.
Fixes https://github.com/streamnative/eng-support-tickets/issues/1881
=> Remove unused log conf

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: autorecovery datadog annotation bug

charts/sn-platform-slim/templates/_helpers.tpl, charts/sn-platform-slim/templates/grafana/grafana-deployment.yaml, charts/sn-platform-slim/templates/grafana/grafana-statefulset.yaml, charts/sn-platform-slim/templates/prometheus/prometheus-configmap.yaml, charts/sn-platform-slim/templates/prometheus/prometheus-statefulset.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/_helpers.tpl, charts/sn-platform/templates/grafana/grafana-deployment.yaml, charts/sn-platform/templates/grafana/grafana-statefulset.yaml, charts/sn-platform/templates/prometheus/prometheus-configmap.yaml, charts/sn-platform/templates/prometheus/prometheus-statefulset.yaml, charts/sn-platform/values.yaml
Allow external non-Istio prometheus and build-in prometheus to scrape Pulsar metrics simultaneously
- Disable Istio Injection on Prom and Grafana when mergeMetrics enabled
- Scrape Metrics with http when mergeMetrics enabled
=> Make build-in prom compatible with mergeMetrics feature

charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> feat: support kop proxy in chart

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> feat: support rackAwareTopologyLabels field on bk

charts/sn-platform-slim/templates/grafana/grafana-deployment.yaml, charts/sn-platform-slim/templates/streamnative-console/streamnative-console-initialize.yaml, charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/grafana/grafana-statefulset.yaml, charts/sn-platform/templates/streamnative-console/streamnative-console-initialize.yaml, charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml, charts/sn-platform/templates/vault/vault-initialize-public-key.yaml, charts/sn-platform/templates/vault/vault-initialize.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> fix: support some missing configs on console, vault and grafana components

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml, charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml
Fixes 
Fix the issue involed from the PR https://github.com/streamnative/charts/pull/1191
*(or)*
*(or)*
*(example:)*
Need to update …
=> Fix console

charts/sn-platform/templates/_helpers.tpl
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> support auth with both jwt and vault

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/values.yaml
```
$ helm template sn-platform-slim | grep -A 10 -B 3 minReadySeconds
level: INFO
format: text
pod:
minReadySeconds: 1
serviceAccountName: release-name-sn-platform-slim-bookie-acct
labels:
app: sn-platform-slim
release: release-name
cluster: release-name-sn-platform-slim
component: bookie
annotations:
prometheus.io/scrape: "true"
prometheus.io/port: "8000"
$ helm template sn-platform | grep -A 10 -B 3 minReadySeconds
level: INFO
format: text
pod:
minReadySeconds: 1
serviceAccountName: release-name-sn-platform-bookie-acct
labels:
app: sn-platform
release: release-name
cluster: release-name-sn-platform
component: bookie
annotations:
prometheus.io/scrape: "true"
prometheus.io/port: "8000"
```
=> Add min ready seconds for bookkeeper

charts/sn-platform-slim/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform-slim/templates/broker/broker-cluster.yaml, charts/sn-platform-slim/templates/proxy/proxy-cluster.yaml, charts/sn-platform-slim/templates/pulsar-coordinator/pulsar-coordinator.yaml, charts/sn-platform-slim/templates/zookeeper/zookeeper-cluster.yaml, charts/sn-platform/templates/bookkeeper/bookkeeper-cluster.yaml, charts/sn-platform/templates/broker/broker-cluster.yaml, charts/sn-platform/templates/proxy/proxy-cluster.yaml, charts/sn-platform/templates/pulsar-coordinator/pulsar-coordinator.yaml, charts/sn-platform/templates/zookeeper/zookeeper-cluster.yaml
If not set images.coordinator, will use images of every component
=> Allow unset coordinator image

charts/sn-platform-slim/templates/streamnative-console/streamnative-console-statefulset.yaml, charts/sn-platform-slim/values.yaml, charts/sn-platform/templates/streamnative-console/streamnative-console-statefulset.yaml, charts/sn-platform/values.yaml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Upgrade private console version, and support update password
